# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont, QFontDatabase
from PyQt5.QtWidgets import * 
from PyQt5.QtGui import * 
from PyQt5.QtCore import Qt
import sys
import time
import pandas as pd
import random
from ClueWindow1 import Ui_ClueWindow
from DDWindow2 import Ui_DDWindow
from PyQt5.QtCore import QProcess
import RPi.GPIO as GPIO
from FinalJWindow2 import Ui_FinalJWindow
import pygame
from CloseWindow1 import Ui_CloseWindow
from FinalJWagersWindow1 import Ui_FinalJWagersWindow
import subprocess
from PyQt5.QtCore import QTimer

pygame.init()

#TODO: this may not be used at all so if not, delete it
file_extension = "C:/Users/elija/OneDrive/Desktop/PythonScripts/JeopardyProjectRepo/JeopardyPi/"

#indicates regular jeopardy or double jeopardy
gameRound = 1

DDtemp = "foo"
cat1NameComp = "foo"
cat2NameComp = "foo"

cat1Index = 0
cat2Index = 0
cat3Index = 0
cat4Index = 0
cat5Index = 0
cat6Index = 0

df = pd.read_excel('Questions/JeopardyTeenQs.xlsx', sheet_name='Sheet1', header=None)

#############################################################################################################
#The purpose of this next section is to guarantee the correct amount of daily doubles as well as unique categories
#TODO: improve this, it's a stupid implementation
#############################################################################################################
def initCluesAndCats(round):
       global df
       global cat1Index
       global cat2Index
       global cat3Index
       global cat4Index
       global cat5Index
       global cat6Index


       if round == 1:
         df = pd.read_excel('Questions/JeopardyTeenQs.xlsx', sheet_name='Sheet1', header=None)
       if round == 2:
         df = pd.read_excel('Questions/DoubleJeopardyTeenQs.xlsx', sheet_name='Sheet1', header=None)
       num_rows = df.shape[0]

       while True:
                #These are which indeces the categories and questions are pulled from the df
                cat1Index = random.randrange(0,num_rows-4,5)
                cat2Index = random.randrange(0,num_rows-4,5)
                cat3Index = random.randrange(0,num_rows-4,5)
                cat4Index = random.randrange(0,num_rows-4,5)
                cat5Index = random.randrange(0,num_rows-4,5)
                cat6Index = random.randrange(0,num_rows-4,5)
                DDcount = 0
                unique = True
                for i in range(1, 7): #for each of the 6 categories
                        for j in range(0,5): #for each question within the category
                                exec(f'global DDtemp; DDtemp = df.iloc[cat{i}Index + {j}, 2]')
                                print(DDtemp)
                                if DDtemp == "yes":
                                        DDcount += 1
                for i in range(1,6):
                        for j in range(i+1,7):
                                #TODO: these cat1NameComp and cat2NameComp shouldn't have to be global
                                exec(f'global cat1NameComp; cat1NameComp = df.iloc[cat{i}Index, 3]')
                                exec(f'global cat2NameComp; cat2NameComp = df.iloc[cat{j}Index, 3]')
                                #uncomment these print functions to see the comparisons it's making
                                #print(cat1NameComp)
                                #print(cat2NameComp +"\n\n")
                                if(cat1NameComp == cat2NameComp):
                                        unique = False
                print("\n\n")
                if(DDcount == gameRound and unique == True):
                        break

player1Score = 0
player2Score = 0
player3Score = 0
player4Score = 0
player5Score = 0

#keeps track of which prompts have been shown so they aren't shown twice
answered = [[0,0,0,0,0], 
            [0,0,0,0,0], 
            [0,0,0,0,0], 
            [0,0,0,0,0], 
            [0,0,0,0,0], 
            [0,0,0,0,0]]

DDamount = ""
totalCluesFinished = 0

buzzable = False #whether or not input from player buzzers should do anything
canBuzzIn = [True, True, True, True, True] #used to stop player from buzzing in after getting it wrong
lastBuzzTime = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] #used for the 0.25 second delay for buzzing early
mostRecentBuzz = 0 #who buzzed in most recently (who should gain or lose money)
mostRecentCorrect = 1 #who was correct most recently (who gets the Daily Double) #this starts at 1 in case the dailydouble is the first clue clicked

alexSeesClue = False #used to determine if alex's buzzer should do anything (if he can't see the clue, nothing's been clicked)
clueIndex = 0 #TODO: this could break some stuff; this is so alexBuzzerPressedOrReleased() knows which clue to show to players
clueGlobal = 0 #so alexBuzzerPressedOrReleased() knows which clue to show players
alexBuzzerPressedFirst = True #used to prevent alex from showing indicators before the clue appears

playerScoreDD = 0

finalIndex = 0
wagerAmount = ""
scoresArray = [(player1Score, "Player1"), (player2Score, "Player2"), (player3Score, "Player3"), (player4Score, "Player4"), (player5Score, "Player5")]
index = 0


class Ui_MainWindow(object):

        #TODO: a lot of this final Jeopardy stuff is probably really poorly written, but it worked on my laptop
    def correctOrIncorrect(self, correct):
         global player1Score
         global player2Score
         global player3Score
         global player4Score
         global player5Score
         global index
         global wagerAmount
         global scoresArray
         
         if correct:
                if scoresArray[index][1] == "Player1":
                        player1Score = player1Score + int(wagerAmount)
                if scoresArray[index][1] == "Player2":
                        player2Score = player2Score + int(wagerAmount)
                if scoresArray[index][1] == "Player3":
                        player3Score = player3Score + int(wagerAmount)
                if scoresArray[index][1] == "Player4":
                        player4Score = player4Score + int(wagerAmount)
                if scoresArray[index][1] == "Player5":
                        player5Score = player5Score + int(wagerAmount)
         else:
                if scoresArray[index][1] == "Player1":
                        player1Score = player1Score - int(wagerAmount)
                if scoresArray[index][1] == "Player2":
                        player2Score = player2Score - int(wagerAmount)
                if scoresArray[index][1] == "Player3":
                        player3Score = player3Score - int(wagerAmount)
                if scoresArray[index][1] == "Player4":
                        player4Score = player4Score - int(wagerAmount)
                if scoresArray[index][1] == "Player5":
                        player5Score = player5Score - int(wagerAmount)
                
         self.setScores("self.FinalJWagersWindowui")

         index = index + 1
         wagerAmount = ""

         if index == len(scoresArray):
                self.FinalJWagersWindowui.correctButton.setVisible(False)
                self.FinalJWagersWindowui.incorrectButton.setVisible(False)
                scoresArray = [(player1Score, "Player1"), (player2Score, "Player2"), (player3Score, "Player3"), (player4Score, "Player4"), (player5Score, "Player5")]
                scoresArray = sorted(scoresArray, key=lambda x: x[0])
                self.FinalJWagersWindowui.ReponseLabel.setText(scoresArray[4][1] + " is the winner!")
                self.FinalJWagersWindowui.PS_ClueLabel.setText(scoresArray[4][1] + " is the winner!")
         else:
                self.FinalJWagersWindowui.button0.setVisible(True)
                self.FinalJWagersWindowui.button1.setVisible(True)
                self.FinalJWagersWindowui.button2.setVisible(True)
                self.FinalJWagersWindowui.button3.setVisible(True)
                self.FinalJWagersWindowui.button4.setVisible(True)
                self.FinalJWagersWindowui.button5.setVisible(True)
                self.FinalJWagersWindowui.button6.setVisible(True)
                self.FinalJWagersWindowui.button7.setVisible(True)
                self.FinalJWagersWindowui.button8.setVisible(True)
                self.FinalJWagersWindowui.button9.setVisible(True)
                self.FinalJWagersWindowui.buttonDEL.setVisible(True)
                self.FinalJWagersWindowui.buttonENTER.setVisible(True)
                self.FinalJWagersWindowui.correctButton.setVisible(False)
                self.FinalJWagersWindowui.incorrectButton.setVisible(False)
                self.FinalJWagersWindowui.ReponseLabel.setText("Enter " + scoresArray[index][1] + "'s wager: $" + wagerAmount)


    #this function handles all the button presses within the DailyDouble window. It's probably poorly written but it works
    def wagersButton(self, button):
          global wagerAmount
          global index

          maxWager = scoresArray[index][0]

          if button == "DEL" and wagerAmount != "":
                 wagerAmount = wagerAmount[:-1]
          elif button == "DEL" and wagerAmount == "":
                 pass
          elif button == "ENTER" and wagerAmount != "":
                 if int(wagerAmount) <= maxWager and int(wagerAmount) >= 5:
                        self.FinalJWagersWindowui.button0.setVisible(False)
                        self.FinalJWagersWindowui.button1.setVisible(False)
                        self.FinalJWagersWindowui.button2.setVisible(False)
                        self.FinalJWagersWindowui.button3.setVisible(False)
                        self.FinalJWagersWindowui.button4.setVisible(False)
                        self.FinalJWagersWindowui.button5.setVisible(False)
                        self.FinalJWagersWindowui.button6.setVisible(False)
                        self.FinalJWagersWindowui.button7.setVisible(False)
                        self.FinalJWagersWindowui.button8.setVisible(False)
                        self.FinalJWagersWindowui.button9.setVisible(False)
                        self.FinalJWagersWindowui.buttonDEL.setVisible(False)
                        self.FinalJWagersWindowui.buttonENTER.setVisible(False)
                        self.FinalJWagersWindowui.correctButton.setVisible(True)
                        self.FinalJWagersWindowui.incorrectButton.setVisible(True)
                 else:
                        pass
          elif button == "0" and wagerAmount == "0":
                 pass
          elif button == "ENTER" and wagerAmount == "":
                 pass
          else: 
                if int(wagerAmount + button) <= maxWager:
                         wagerAmount = wagerAmount + button
          self.FinalJWagersWindowui.ReponseLabel.setText("Enter " + scoresArray[index][1] + "'s wager: $" + wagerAmount)

    def showFinalClue(self):
           self.FinalJWindowui.CategoryLabel.setText(str(df.iloc[finalIndex, 3]))
           font = QtGui.QFont()
           font.setBold(True)
           font.setFamily("Roman")
           font.setPointSize(30)
           self.FinalJWindowui.PS_ClueLabel.setFont(font)
           self.FinalJWindowui.PS_ClueLabel.setText(str(df.iloc[finalIndex, 5]))
           self.FinalJWindowui.AS_ClueLabel.setText(str(df.iloc[finalIndex, 5]))
           self.FinalJWindowui.ReponseLabel.setText(str(df.iloc[finalIndex, 6]))
           #the button will be hidden to show the "Start Time" button
           self.FinalJWindowui.showClueButton.setVisible(False)
           self.FinalJWindowui.startMusicButton.setVisible(True)

    def startMusicClicked(self):
        self.startMusicButton.setVisible(False)

        pygame.mixer.music.load("Sounds/FinalJeopardy_Think.mp3")
        pygame.mixer.music.play()
        
        self.timer = QTimer()
        self.timer.setSingleShot(True)
        self.timer.timeout.connect(self.timeFinished)
        self.timer.start(30000) # 30,000 milliseconds = 30 seconds
        

    def timeFinished(self):
        global player1Score
        global player2Score
        global player3Score
        global player4Score
        global player5Score
        global scoresArray
        global nextWager

        self.FinalJWagersWindow = QtWidgets.QMainWindow()
        self.FinalJWagersWindowui = Ui_FinalJWagersWindow()
        self.FinalJWagersWindowui.setupUi(self.FinalJWagersWindow)
        self.FinalJWagersWindow.setWindowFlags(Qt.FramelessWindowHint)
        self.FinalJWagersWindow.show()

        self.setScores("self.FinalJWagersWindowui")

        self.FinalJWagersWindowui.CloseButton.clicked.connect(self.closedButtonClicked)
        self.FinalJWagersWindowui.button0.clicked.connect(lambda: self.wagersButton(button="0"))
        self.FinalJWagersWindowui.button1.clicked.connect(lambda: self.wagersButton(button="1"))
        self.FinalJWagersWindowui.button2.clicked.connect(lambda: self.wagersButton(button="2"))
        self.FinalJWagersWindowui.button3.clicked.connect(lambda: self.wagersButton(button="3"))
        self.FinalJWagersWindowui.button4.clicked.connect(lambda: self.wagersButton(button="4"))
        self.FinalJWagersWindowui.button5.clicked.connect(lambda: self.wagersButton(button="5"))
        self.FinalJWagersWindowui.button6.clicked.connect(lambda: self.wagersButton(button="6"))
        self.FinalJWagersWindowui.button7.clicked.connect(lambda: self.wagersButton(button="7"))
        self.FinalJWagersWindowui.button8.clicked.connect(lambda: self.wagersButton(button="8"))
        self.FinalJWagersWindowui.button9.clicked.connect(lambda: self.wagersButton(button="9"))
        self.FinalJWagersWindowui.buttonDEL.clicked.connect(lambda: self.wagersButton(button="DEL"))
        self.FinalJWagersWindowui.buttonENTER.clicked.connect(lambda: self.wagersButton(button="ENTER"))
        self.FinalJWagersWindowui.correctButton.clicked.connect(lambda: self.correctOrIncorrect(correct=True))
        self.FinalJWagersWindowui.incorrectButton.clicked.connect(lambda: self.correctOrIncorrect(correct=False))
        self.FinalJWagersWindowui.correctButton.setVisible(False)
        self.FinalJWagersWindowui.incorrectButton.setVisible(False)

        scoresArray = [(player1Score, "Player1"), (player2Score, "Player2"), (player3Score, "Player3"), (player4Score, "Player4"), (player5Score, "Player5")]
        #sort elements
        scoresArray = sorted(scoresArray, key=lambda x: x[0])
        # Remove elements with integer <= 0
        scoresArray = [item for item in scoresArray if item[0] > 0]
        print(scoresArray)    

        self.FinalJWagersWindowui.ReponseLabel.setText("Enter " + scoresArray[0][1] + "'s wager: $" + wagerAmount)

    def initFinalJeopRound(self):
         global df
         global finalIndex

        #show the window
         self.FinalJWindow = QtWidgets.QMainWindow()
         self.FinalJWindowui = Ui_FinalJWindow()
         self.FinalJWindowui.setupUi(self.FinalJWindow)
         self.FinalJWindow.setWindowFlags(Qt.FramelessWindowHint)
         self.FinalJWindow.show()

         self.FinalJWindowui.CloseButton.clicked.connect(self.closeButtonPressed)
         self.FinalJWindowui.showClueButton.clicked.connect(self.showFinalClue)

         df = pd.read_excel('Questions/FinalJeopardyTeenQs.xlsx', sheet_name='Sheet1', header=None)
         num_rows = df.shape[0]
         #TODO: swap comments on following 2 lines. This is here so I don't view all the final jeopardies in dev
         #finalIndex = random.randrange(0, num_rows)
         finalIndex = 0
         
         self.FinalJWindowui.CategoryLabel.setText("")
         self.FinalJWindowui.PS_ClueLabel.setText(str(df.iloc[finalIndex, 3]))
         self.FinalJWindowui.AS_ClueLabel.setText("The category is: " + str(df.iloc[finalIndex, 3]))

         self.setScores("self.FinalJWindowui")
    
    def checkEndRound2(self):
           if totalCluesFinished == 60:
                 print("END OF DOUBLE JEOPARDY ROUND")
                 self.initFinalJeopRound()
    
    #TODO: change all of this so that is uses setVisible() which I think will work better
    def hideAllButBuzzed(self, player):
        for i in range(1,6):
            if i != player:
                #TODO: this is kidna weird bc I did it two different ways but it should work. Dunno why it's not
                #exec(f'self.ClueWindowui.PS_P{i}Money.setStyleSheet("background-color: #060CE9; color: #060CE9;")')
                #exec(f'self.ClueWindowui.PS_P{i}Name.setStyleSheet("background-color: #060CE9; color: #060CE9;")')
                #exec(f'self.ClueWindowui.AS_P{i}Money.setStyleSheet("background-color: #060CE9; color: #060CE9;")')
                #exec(f'self.ClueWindowui.AS_P{i}Name.setStyleSheet("background-color: #060CE9; color: #060CE9;")')
                #exec(f'self.ClueWindowui.PS_P{i}Money.setText(".")')
                #exec(f'self.ClueWindowui.PS_P{i}Name.setText(".")')
                #exec(f'self.ClueWindowui.AS_P{i}Money.setText(".")')
                #exec(f'self.ClueWindowui.AS_P{i}Name.setText(".")')


                #exec(f'self.ClueWindowui.PS_P{i}Money.setText("")')
                #exec(f'self.ClueWindowui.PS_P{i}Name.setText("")')
                #exec(f'self.ClueWindowui.AS_P{i}Money.setText("")')
                #exec(f'self.ClueWindowui.AS_P{i}Name.setText("")')
                
                #I think the rest of this is unnecessary.
                #exec(f'self.ClueWindowui.PS_P{i}Name.update()')
                #exec(f'self.ClueWindowui.PS_P{i}Money.update()')
                #exec(f'self.ClueWindowui.AS_P{i}Name.update()')
                #exec(f'self.ClueWindowui.AS_P{i}Money.update()')
                #QApplication.processEvents()
                exec(f'self.ClueWindowui.PS_P{i}Money.setVisible(False)')
                exec(f'self.ClueWindowui.PS_P{i}Name.setVisible(False)')
                exec(f'self.ClueWindowui.AS_P{i}Money.setVisible(False)')
                exec(f'self.ClueWindowui.AS_P{i}Name.setVisible(False)')
                
                
    
    #TODO: I'm probably not supposed to use exec() this much but i really love it and idk how else to do this. 
    #I am bad at programming, but it's working so far
    #this is to update player scores on a given screen so you don't have these huge blocks everytime you want to show a new screen
    def setScores(self, ui):
        #TODO: could be done with for loop (at leat the first part)
          #exec(f'{ui}.AS_P1Name.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
          #exec(f'{ui}.AS_P2Name.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
          #exec(f'{ui}.AS_P3Name.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
          #exec(f'{ui}.AS_P4Name.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
          #exec(f'{ui}.AS_P5Name.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
          #exec(f'{ui}.PS_P1Name.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
          #exec(f'{ui}.PS_P2Name.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
          #exec(f'{ui}.PS_P3Name.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
          #exec(f'{ui}.PS_P4Name.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
          #exec(f'{ui}.PS_P5Name.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
          #exec(f'{ui}.AS_P1Name.setText("Player1")')
          #exec(f'{ui}.AS_P2Name.setText("Player2")')
          #exec(f'{ui}.AS_P3Name.setText("Player3")')
          #exec(f'{ui}.AS_P4Name.setText("Player4")')
          #exec(f'{ui}.AS_P5Name.setText("Player5")')
          #exec(f'{ui}.PS_P1Name.setText("Player1")')
          #exec(f'{ui}.PS_P2Name.setText("Player2")')
          #exec(f'{ui}.PS_P3Name.setText("Player3")')
          #exec(f'{ui}.PS_P4Name.setText("Player4")')
          #exec(f'{ui}.PS_P5Name.setText("Player5")')
          
          for i in range(1,6):
                exec(f'self.ClueWindowui.PS_P{i}Money.setVisible(True)')
                exec(f'self.ClueWindowui.PS_P{i}Name.setVisible(True)')
                exec(f'self.ClueWindowui.AS_P{i}Money.setVisible(True)')
                exec(f'self.ClueWindowui.AS_P{i}Name.setVisible(True)')

          if player1Score < 0:
                exec(f'{ui}.PS_P1Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 0, 0);")')
                exec(f'{ui}.PS_P1Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 0, 0);")')
                exec(f'{ui}.AS_P1Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 0, 0);")')
                exec(f'{ui}.PS_P1Money.setText("-$" + str(player1Score)[1:])')
                exec(f'{ui}.AS_P1Money.setText("-$" + str(player1Score)[1:])')
          else:
                exec(f'{ui}.PS_P1Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
                exec(f'{ui}.AS_P1Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
                exec(f'{ui}.PS_P1Money.setText("$" + str(player1Score))')
                exec(f'{ui}.AS_P1Money.setText("$" + str(player1Score))')
          if player2Score < 0:
                exec(f'{ui}.PS_P2Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 0, 0);")')
                exec(f'{ui}.AS_P2Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 0, 0);")')
                exec(f'{ui}.PS_P2Money.setText("-$" + str(player2Score)[1:])')
                exec(f'{ui}.AS_P2Money.setText("-$" + str(player2Score)[1:])')
          else:
                exec(f'{ui}.PS_P2Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
                exec(f'{ui}.AS_P2Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
                exec(f'{ui}.PS_P2Money.setText("$" + str(player2Score))')
                exec(f'{ui}.AS_P2Money.setText("$" + str(player2Score))')
          if player3Score < 0:
                exec(f'{ui}.PS_P3Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 0, 0);")')
                exec(f'{ui}.AS_P3Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 0, 0);")')
                exec(f'{ui}.PS_P3Money.setText("-$" + str(player3Score)[1:])')
                exec(f'{ui}.AS_P3Money.setText("-$" + str(player3Score)[1:])')
          else:
                exec(f'{ui}.PS_P3Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
                exec(f'{ui}.AS_P3Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
                exec(f'{ui}.PS_P3Money.setText("$" + str(player3Score))')
                exec(f'{ui}.AS_P3Money.setText("$" + str(player3Score))')
          if player4Score < 0:
                exec(f'{ui}.PS_P4Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 0, 0);")')
                exec(f'{ui}.AS_P4Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 0, 0);")')
                exec(f'{ui}.PS_P4Money.setText("-$" + str(player4Score)[1:])')
                exec(f'{ui}.AS_P4Money.setText("-$" + str(player4Score)[1:])')
          else:
                exec(f'{ui}.PS_P4Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
                exec(f'{ui}.AS_P4Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
                exec(f'{ui}.PS_P4Money.setText("$" + str(player4Score))')
                exec(f'{ui}.AS_P4Money.setText("$" + str(player4Score))')
          if player5Score < 0:
                exec(f'{ui}.PS_P5Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 0, 0);")')
                exec(f'{ui}.AS_P5Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 0, 0);")')
                exec(f'{ui}.PS_P5Money.setText("-$" + str(player5Score)[1:])')
                exec(f'{ui}.AS_P5Money.setText("-$" + str(player5Score)[1:])')
          else:
                exec(f'{ui}.PS_P5Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
                exec(f'{ui}.AS_P5Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
                exec(f'{ui}.PS_P5Money.setText("$" + str(player5Score))')
                exec(f'{ui}.AS_P5Money.setText("$" + str(player5Score))')
    
    def alexBuzzerPressedOrReleased(self, channel):
           global lastBuzzTime
           global alexSeesClue
           global buzzable
           global alexBuzzerPressedFirst
           global canBuzzIn
           global mostRecentBuzz
           global totalCluesFinished

           print(channel)

           if not alexSeesClue:
                        return #do nothing; not a time alex can buzz
           
           if GPIO.input(channel):
                 #Button released (rising edge)
                 if not alexBuzzerPressedFirst:
                     return #the button must be pressed before it can be released
                 
                 #TODO: this is probably a stupid solution that won't work
                 while not self.ClueWindowui.ReadyIndicatorL.isVisible():
                        self.ClueWindowui.ReadyIndicatorL.setVisible(True)
                 while not self.ClueWindowui.ReadyIndicatorR.isVisible():
                        self.ClueWindowui.ReadyIndicatorR.setVisible(True)
                 self.ClueWindowui.ReadyIndicatorL.update()
                 self.ClueWindowui.ReadyIndicatorR.update()
                 QApplication.processEvents()
                 
                 #update the time in lastBuzzTime
                 buzzable = True
                 lastBuzzTime[5] = time.time()
                 #alexSeesClue = False #not sure if this should be here
                 alexBuzzerPressedFirst = False
           else:
                 # Button pressed (falling edge)
                 #if it's been at least three seconds since the indicators have been shown
                 if buzzable and (time.time() - lastBuzzTime[5] >= 3):
                        #close the clue window when alex buzzes
                        exec(f'self.Cat{category}Clue{clue}B.setText("")')
                        self.ClueWindow.close()
                        alexSeesClue = False
                        canBuzzIn = [True, True, True, True, True]
                        mostRecentBuzz = 0
                        buzzable = False #nobody else should be able to buzz in until next question
                        self.setScores("self")
                        totalCluesFinished += 1
                        self.checkEndRound1()
                        self.checkEndRound2()
                        alexSeesClue = False
                 else:
                        alexBuzzerPressedFirst = True
                        self.ClueWindowui.PS_ClueLabel.setText(str(df.iloc[clueIndex+clueGlobal-1, 5])) #show clue
                 

    
    def playerBuzzerPressed(self, channel):
           global canBuzzIn
           global mostRecentBuzz
           global buzzable
           global lastBuzzTime

           player = 0
           
           #figure out who buzzed in TODO: better implementation
           if channel == 23:
                  player = 1
           if channel == 24:
                  player = 2
           if channel == 25:
                  player = 3
           if channel == 8:
                  player = 4
           if channel == 7:
                  player = 5
        
           if not buzzable: #if you buzzed too early or at a random time
                  lastBuzzTime[player-1] = time.time()
                  return
           curtime = time.time()
           if curtime - lastBuzzTime[player-1] <= 0.25: #I tested this with a 10 second delay and it worked appropriately
                  return #don't update lastBuzzTime since it was buzzable (this is just the penalty delay)
           if  not canBuzzIn[player-1]: #if they already got it wrong, do nothing
                  return
           buzzable = False #nobody else should be able to buzz in until next question or miss
           mostRecentBuzz = player #so we know who to give the money to
           self.hideAllButBuzzed(player)
           #now show the buttons
           self.ClueWindowui.correctButton.setVisible(True)
           self.ClueWindowui.incorrectButton.setVisible(True)
           
                

    
    def initDoubleJeopRound(self):
           #TODO: should tell Alex who gets to select the clue, should do it at beginning of game too
           global gameRound
           global answered
           global mostRecentCorrect
           gameRound = 2
           answered = [[0,0,0,0,0], 
                       [0,0,0,0,0], 
                       [0,0,0,0,0], 
                       [0,0,0,0,0], 
                       [0,0,0,0,0], 
                       [0,0,0,0,0]]
           
           #the person with the lowest score should select the clue; that's also the person who gets the DD if it's first selected
           #if two people are tied for lowest, it's the one with the lower player number
           lowestScore = min(player1Score, player2Score, player3Score, player4Score, player5Score)
           if player1Score == lowestScore:
                  mostRecentCorrect = 1
           elif player2Score == lowestScore:
                  mostRecentCorrect = 2
           elif player3Score == lowestScore:
                  mostRecentCorrect = 3
           elif player4Score == lowestScore:
                  mostRecentCorrect = 4
           else:
                  mostRecentCorrect = 5

           initCluesAndCats(gameRound)
           self.setCategories()
           self.Cat1Clue1B.setText("$400")
           self.Cat2Clue1B.setText("$400")
           self.Cat3Clue1B.setText("$400")
           self.Cat4Clue1B.setText("$400")
           self.Cat5Clue1B.setText("$400")
           self.Cat6Clue1B.setText("$400")
           self.Cat1Clue2B.setText("$800")
           self.Cat2Clue2B.setText("$800")
           self.Cat3Clue2B.setText("$800")
           self.Cat4Clue2B.setText("$800")
           self.Cat5Clue2B.setText("$800")
           self.Cat6Clue2B.setText("$800")
           self.Cat1Clue3B.setText("$1200")
           self.Cat2Clue3B.setText("$1200")
           self.Cat3Clue3B.setText("$1200")
           self.Cat4Clue3B.setText("$1200")
           self.Cat5Clue3B.setText("$1200")
           self.Cat6Clue3B.setText("$1200")
           self.Cat1Clue4B.setText("$1600")
           self.Cat2Clue4B.setText("$1600")
           self.Cat3Clue4B.setText("$1600")
           self.Cat4Clue4B.setText("$1600")
           self.Cat5Clue4B.setText("$1600")
           self.Cat6Clue4B.setText("$1600")
           self.Cat1Clue5B.setText("$2000")
           self.Cat2Clue5B.setText("$2000")
           self.Cat3Clue5B.setText("$2000")
           self.Cat4Clue5B.setText("$2000")
           self.Cat5Clue5B.setText("$2000")
           self.Cat6Clue5B.setText("$2000")
        
    
    def checkEndRound1(self):
           if totalCluesFinished == 30:
                 print("END OF JEOPARDY ROUND")
                 self.initDoubleJeopRound()

#this function handles all the button presses within the DailyDouble window. It's probably poorly written but it works
    def DDbutton(self, button, category=None, clue=None, amount=None, dailyDouble=None, DDplayer=""):
          global DDamount
          global playerScoreDD

          maxWager = max(playerScoreDD, 1000*gameRound)

          if button == "DEL" and DDamount != "":
                 DDamount = DDamount[:-1]
          elif button == "DEL" and DDamount == "":
                 pass
          elif button == "ENTER" and DDamount != "":
                 if int(DDamount) <= maxWager and int(DDamount) >= 5:
                        self.showClueWindow(category=category, clue=clue, amount=int(DDamount), dailyDouble="no", DDplayer=mostRecentCorrect)
                        self.DDWindow.close()
                        DDamount = ""
                 else:
                        pass
          elif button == "0" and DDamount == "":
                 pass
          elif button == "ENTER" and DDamount == "":
                 pass
          else: 
                if int(DDamount + button) <= maxWager:
                         DDamount = DDamount + button

          self.DDWindowui.AmountLabel.setText("$" + DDamount)
          
          

    def showDDWindow(self, category, clue, amount, dailyDouble, DDplayer=""):
         pygame.mixer.music.load("Sounds/DailyDouble.mp3")
         pygame.mixer.music.play()
        
         #show the window
         self.DDWindow = QtWidgets.QMainWindow()
         self.DDWindowui = Ui_DDWindow()
         self.DDWindowui.setupUi(self.DDWindow)
         self.DDWindow.setWindowFlags(Qt.FramelessWindowHint)
         self.DDWindow.show()

          #link buttons
         self.DDWindowui.CloseButton.clicked.connect(self.closeButtonPressed)
         self.DDWindowui.button0.clicked.connect(lambda: self.DDbutton(button="0"))
         self.DDWindowui.button1.clicked.connect(lambda: self.DDbutton(button="1"))
         self.DDWindowui.button2.clicked.connect(lambda: self.DDbutton(button="2"))
         self.DDWindowui.button3.clicked.connect(lambda: self.DDbutton(button="3"))
         self.DDWindowui.button4.clicked.connect(lambda: self.DDbutton(button="4"))
         self.DDWindowui.button5.clicked.connect(lambda: self.DDbutton(button="5"))
         self.DDWindowui.button6.clicked.connect(lambda: self.DDbutton(button="6"))
         self.DDWindowui.button7.clicked.connect(lambda: self.DDbutton(button="7"))
         self.DDWindowui.button8.clicked.connect(lambda: self.DDbutton(button="8"))
         self.DDWindowui.button9.clicked.connect(lambda: self.DDbutton(button="9"))
         self.DDWindowui.buttonDEL.clicked.connect(lambda: self.DDbutton(button="DEL"))
         self.DDWindowui.buttonENTER.clicked.connect(lambda: self.DDbutton(button="ENTER", category=category, clue=clue, amount=amount, DDplayer=""))
         
         #used to update label
         if category == 1:
                 clueIndex = cat1Index
         if category == 2:
                 clueIndex = cat2Index
         if category == 3:
                 clueIndex = cat3Index
         if category == 4:
                 clueIndex = cat4Index
         if category == 5:
                  clueIndex = cat5Index
         if category == 6:
                 clueIndex = cat6Index 

         exec(f'global playerScoreDD; playerScoreDD = player{mostRecentCorrect}Score')       
         maxWager = max(playerScoreDD, 1000*gameRound)

         #update window with correct info
         self.setScores("self.DDWindowui")

         self.DDWindowui.CategoryLabel.setText(str(df.iloc[clueIndex, 3]))
         self.DDWindowui.PS_Instructions.setText(f"Player{mostRecentCorrect}, enter your wager with the keypad. Your wager must be at least $5 and no more than $" + str(maxWager) + ".")
         self.DDWindowui.AS_Instructions.setText(f"Player{mostRecentCorrect}, found the Daily Double!")
         ##TODO: change this next line on future versions bc i updated the .ui file
         self.DDWindowui.AS_DecoLabel3.setText("Their wager must be at least $5 and no more than $" + str(maxWager) + ".")



          
    def showClueWindow(self, category, clue, amount, dailyDouble, DDplayer=0):
         global answered
         global buzzable
         global alexSeesClue
         global clueIndex
         global clueGlobal
         global alexBuzzerPressedFirst

         #if clue has already been given, do nothing
         if(answered[category-1][clue-1] == 1):
               return
         
         #if this question is a Daily Double
         if(dailyDouble == "yes"):
               print("Daily Double clicked")
               self.showDDWindow(category = category, clue=clue, amount=amount, dailyDouble=dailyDouble, DDplayer="")
         elif DDplayer != 0: #this means that it's a DailyDouble and has already been wagered. No fancy buzzer stuff this time
                #All the following stuff is redundant but I'm not caring right now as long as it works
                #show the window
                self.ClueWindow = QtWidgets.QMainWindow()
                self.ClueWindowui = Ui_ClueWindow()
                self.ClueWindowui.setupUi(self.ClueWindow)
                self.ClueWindow.setWindowFlags(Qt.FramelessWindowHint)
                self.ClueWindow.show()

                #update window with correct info
                self.setScores("self.ClueWindowui")

                #link buttons
                self.ClueWindowui.CloseButton.clicked.connect(self.closeButtonPressed)
                self.ClueWindowui.correctButton.clicked.connect(lambda: self.Correct(category = category, clue = clue, amount = amount, DDplayer=DDplayer))
                self.ClueWindowui.incorrectButton.clicked.connect(lambda: self.Incorrect(category = category, clue = clue, amount = amount, DDplayer=DDplayer))
                #initially, the buttons should be hidden
                self.ClueWindowui.correctButton.setVisible(False)
                self.ClueWindowui.incorrectButton.setVisible(False)

                if category == 1:
                        clueIndex = cat1Index
                if category == 2:
                        clueIndex = cat2Index
                if category == 3:
                        clueIndex = cat3Index
                if category == 4:
                        clueIndex = cat4Index
                if category == 5:
                        clueIndex = cat5Index
                if category == 6:
                        clueIndex = cat6Index

                self.ClueWindowui.AS_ClueLabel.setText(str(df.iloc[clueIndex+clue-1, 5]))
                self.ClueWindowui.PS_ClueLabel.setText(str(df.iloc[clueIndex+clue-1, 5]))
                self.ClueWindowui.ReponseLabel.setText(str(df.iloc[clueIndex+clue-1, 6]))
                self.ClueWindowui.CategoryLabel.setText(str(df.iloc[clueIndex, 3]))
                self.ClueWindowui.AmountLabel.setText("$" + str(amount))

                answered[category-1][clue-1] = 1 #used to clear the button later
         else:
                #show the window
                self.ClueWindow = QtWidgets.QMainWindow()
                self.ClueWindowui = Ui_ClueWindow()
                self.ClueWindowui.setupUi(self.ClueWindow)
                self.ClueWindow.setWindowFlags(Qt.FramelessWindowHint)
                self.ClueWindow.show()

                #update window with correct info
                self.setScores("self.ClueWindowui")

                #link buttons
                self.ClueWindowui.CloseButton.clicked.connect(self.closeButtonPressed)
                self.ClueWindowui.correctButton.clicked.connect(lambda: self.Correct(category = category, clue = clue, amount = amount))
                self.ClueWindowui.incorrectButton.clicked.connect(lambda: self.Incorrect(category = category, clue = clue, amount = amount))
                #initially, the buttons should be hidden
                self.ClueWindowui.correctButton.setVisible(False)
                self.ClueWindowui.incorrectButton.setVisible(False)

                if category == 1:
                        clueIndex = cat1Index
                if category == 2:
                        clueIndex = cat2Index
                if category == 3:
                        clueIndex = cat3Index
                if category == 4:
                        clueIndex = cat4Index
                if category == 5:
                        clueIndex = cat5Index
                if category == 6:
                        clueIndex = cat6Index
                clueGlobal = clue #to get the value into the global var?

                #initially the indicators are hidden
                self.ClueWindowui.ReadyIndicatorL.setVisible(False)
                self.ClueWindowui.ReadyIndicatorR.setVisible(False)

                self.ClueWindowui.AS_ClueLabel.setText(str(df.iloc[clueIndex+clue-1, 5]))
                #self.ClueWindowui.PS_ClueLabel.setText(str(df.iloc[clueIndex+clue-1, 5]))
                self.ClueWindowui.ReponseLabel.setText(str(df.iloc[clueIndex+clue-1, 6]))
                self.ClueWindowui.CategoryLabel.setText(str(df.iloc[clueIndex, 3]))
                self.ClueWindowui.AmountLabel.setText("$" + str(amount))
                
                
                alexBuzzerPressedFirst = False
                alexSeesClue = True
                #buzzable = True #taken care of by alexBuzzerPressedOrReleased()
                answered[category-1][clue-1] = 1 #used to clear the button later

#TODO: Correct and Incorrect functions can be consolidated into one function that only differs in whether the new value is added or subtracted (i think)
    def Correct(self, category, clue, amount, DDplayer=0): 
          #global player1Score
          global totalCluesFinished
          global mostRecentBuzz
          global canBuzzIn
          global mostRecentCorrect
          global buzzable
          global alexSeesClue

          if DDplayer != 0:
                 #i reckon i could use mostRecentCorrect in the following exec() but either way should work
                 exec(f'global player{DDplayer}Score; player{DDplayer}Score += amount')

                 #these shouldn't have to be stated
                 alexSeesClue = False
                 canBuzzIn = [True, True, True, True, True]
                 mostRecentBuzz = 0
                 buzzable = False 

                 self.setScores("self")
                 exec(f'self.Cat{category}Clue{clue}B.setText("")')
                 self.ClueWindow.close()
                 totalCluesFinished += 1
                 self.checkEndRound1()
                 self.checkEndRound2()
                 return


          if mostRecentBuzz == 0: #if nobody answered
                 exec(f'self.Cat{category}Clue{clue}B.setText("")')
                 self.ClueWindow.close()
                 alexSeesClue = False
                 canBuzzIn = [True, True, True, True, True]
                 mostRecentBuzz = 0
                 buzzable = False #nobody else should be able to buzz in until next question
                 self.setScores("self")
                 totalCluesFinished += 1
                 self.checkEndRound1()
                 self.checkEndRound2()
                 return
          
          exec(f'global player{mostRecentBuzz}Score; player{mostRecentBuzz}Score += amount')

          self.setScores("self")
          
          exec(f'self.Cat{category}Clue{clue}B.setText("")')
          self.ClueWindow.close()
          alexSeesClue = False
          canBuzzIn = [True, True, True, True, True]
          mostRecentCorrect = mostRecentBuzz
          mostRecentBuzz = 0
          buzzable = False

          totalCluesFinished += 1
          self.checkEndRound1()
          self.checkEndRound2()
          
#TODO: when Incorrect() is called it shouldn't automatically close the window bc others have a chance to guess
    def Incorrect(self, category, clue, amount, DDplayer=0):
          #global player1Score
          global mostRecentBuzz
          global canBuzzIn
          global totalCluesFinished
          global buzzable
          global alexSeesClue

          if DDplayer != 0:
                 #i reckon i could use mostRecentCorrect in the following exec() but either way should work
                 exec(f'global player{DDplayer}Score; player{DDplayer}Score -= amount')

                 #these shouldn't have to be stated
                 alexSeesClue = False
                 canBuzzIn = [True, True, True, True, True]
                 mostRecentBuzz = 0
                 buzzable = False 

                 self.setScores("self")
                 exec(f'self.Cat{category}Clue{clue}B.setText("")')
                 self.ClueWindow.close()
                 totalCluesFinished += 1
                 self.checkEndRound1()
                 self.checkEndRound2()
                 return
          
          if mostRecentBuzz == 0: #if nobody answered
                 canBuzzIn = [True, True, True, True, True]
                 mostRecentBuzz = 0
                 buzzable = False #nobody else should be able to buzz in until next question
                 self.setScores("self")
                 alexSeesClue = False
                 exec(f'self.Cat{category}Clue{clue}B.setText("")')
                 self.ClueWindow.close()
                 totalCluesFinished += 1
                 self.checkEndRound1()
                 self.checkEndRound2()
                 return #nobody buzzed in so don't continue
          
          exec(f'global player{mostRecentBuzz}Score; player{mostRecentBuzz}Score -= amount')
          self.setScores("self.ClueWindowui")
          #hide buttons again
          self.ClueWindowui.correctButton.setVisible(False)
          self.ClueWindowui.incorrectButton.setVisible(False)
          
          #exec(f'self.Cat{category}Clue{clue}B.setText("")') should be able to delete this
          canBuzzIn[mostRecentBuzz-1] = False #can't buzz in once incorrect
          buzzable = True #others can buzz in after this person missed it
          mostRecentBuzz = 0 #so if incorrect is clicked again, the window closes
          #totalCluesFinished += 1
          #self.checkEndRound1()


    def closeButtonPressed(self):
            #show the window
            self.CloseWindow = QtWidgets.QMainWindow()
            self.CloseWindowui = Ui_CloseWindow()
            self.CloseWindowui.setupUi(self.CloseWindow)
            self.CloseWindow.setWindowFlags(Qt.FramelessWindowHint)
            self.CloseWindow.show()
        
            self.CloseWindowui.closeJButton.clicked.connect(self.closeScreens)
            self.CloseWindowui.shutdownButton.clicked.connect(self.shutdownPi)
            self.CloseWindowui.cancelButton.clicked.connect(self.cancelClose)

    def closeScreens(self):
            MainWindow.close()
            self.ClueWindow.close()
            self.DDWindow.close()
            self.FinalJWindow.close()
            self.FinalJWagersWindow.close()
            self.CloseWindow.close()

    def shutdownPi(self):
           subprocess.call("sudo shutdown -h now", shell=True)

    def cancelClose(self):
           self.CloseWindow.close()

    def setCategories(self):
         self.CatLabel1.setText(str(df.iloc[cat1Index, 3])) 
         self.CatLabel2.setText(str(df.iloc[cat2Index, 3]))
         self.CatLabel3.setText(str(df.iloc[cat3Index, 3]))
         self.CatLabel4.setText(str(df.iloc[cat4Index, 3]))
         self.CatLabel5.setText(str(df.iloc[cat5Index, 3]))
         self.CatLabel6.setText(str(df.iloc[cat6Index, 3]))

    #This is currently the function that's called when a clue button is clicked
    #def showPrompt(self, category, clue):
         #print(str(category) + str (clue))
         #globalCategory = category
         #globalClue = clue
         #self.showClueWindow()
         #self.ReadyIndicatorL.setStyleSheet("background-color: rgb(0, 0, 0);")
         #self.ReadyIndicatorR.setStyleSheet("background-color: rgb(0, 0, 0);")
         #time.sleep(2)
         #elf.ReadyIndicatorL.setStyleSheet("background-color: rgb(255, 0, 255);")
         #self.ReadyIndicatorR.setStyleSheet("background-color: rgb(255, 0, 255);")
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        #MainWindow.resize(1824, 600)
        MainWindow.setGeometry(0,0,1824,600)#you can use this to scoot the window over to see where DD is
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ReadyIndicatorR = QtWidgets.QLabel(self.centralwidget)
        self.ReadyIndicatorR.setGeometry(QtCore.QRect(1004, 0, 20, 600))
        self.ReadyIndicatorR.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ReadyIndicatorR.setText("")
        self.ReadyIndicatorR.setObjectName("ReadyIndicatorR")
        self.ReadyIndicatorL = QtWidgets.QLabel(self.centralwidget)
        self.ReadyIndicatorL.setGeometry(QtCore.QRect(0, 0, 20, 600))
        self.ReadyIndicatorL.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ReadyIndicatorL.setText("")
        self.ReadyIndicatorL.setObjectName("ReadyIndicatorL")
        self.PS_DecoLabel = QtWidgets.QLabel(self.centralwidget)
        self.PS_DecoLabel.setGeometry(QtCore.QRect(20, 540, 984, 60))
        self.PS_DecoLabel.setStyleSheet("background-color: #060CE9;")
        self.PS_DecoLabel.setText("")
        self.PS_DecoLabel.setObjectName("PS_DecoLabel")
        self.PS_P1Name = QtWidgets.QLabel(self.centralwidget)
        self.PS_P1Name.setGeometry(QtCore.QRect(59, 545, 150, 25))

        QFontDatabase.addApplicationFont("Fonts/Swiss 911 Compressed Regular.otf")
        QFontDatabase.addApplicationFont("Fonts/JeopardyPi/Korinna-Regular.otf")
        QFontDatabase.addApplicationFont("Fonts/Univers 75 Black Regular.otf")

        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PS_P1Name.setFont(font)
        self.PS_P1Name.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.PS_P1Name.setAlignment(QtCore.Qt.AlignCenter)
        self.PS_P1Name.setObjectName("PS_P1Name")
        self.PS_P1Money = QtWidgets.QLabel(self.centralwidget)
        self.PS_P1Money.setGeometry(QtCore.QRect(59, 570, 150, 25))
        font = QtGui.QFont()
        font.setFamily("Univers 75 Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.PS_P1Money.setFont(font)
        self.PS_P1Money.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.PS_P1Money.setAlignment(QtCore.Qt.AlignCenter)
        self.PS_P1Money.setObjectName("PS_P1Money")
        self.PS_P2Name = QtWidgets.QLabel(self.centralwidget)
        self.PS_P2Name.setGeometry(QtCore.QRect(248, 545, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PS_P2Name.setFont(font)
        self.PS_P2Name.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.PS_P2Name.setAlignment(QtCore.Qt.AlignCenter)
        self.PS_P2Name.setObjectName("PS_P2Name")
        self.PS_P3Name = QtWidgets.QLabel(self.centralwidget)
        self.PS_P3Name.setGeometry(QtCore.QRect(437, 545, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PS_P3Name.setFont(font)
        self.PS_P3Name.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.PS_P3Name.setAlignment(QtCore.Qt.AlignCenter)
        self.PS_P3Name.setObjectName("PS_P3Name")
        self.PS_P4Name = QtWidgets.QLabel(self.centralwidget)
        self.PS_P4Name.setGeometry(QtCore.QRect(626, 545, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PS_P4Name.setFont(font)
        self.PS_P4Name.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.PS_P4Name.setAlignment(QtCore.Qt.AlignCenter)
        self.PS_P4Name.setObjectName("PS_P4Name")
        self.PS_P5Name = QtWidgets.QLabel(self.centralwidget)
        self.PS_P5Name.setGeometry(QtCore.QRect(815, 545, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PS_P5Name.setFont(font)
        self.PS_P5Name.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.PS_P5Name.setAlignment(QtCore.Qt.AlignCenter)
        self.PS_P5Name.setObjectName("PS_P5Name")
        self.PS_P2Money = QtWidgets.QLabel(self.centralwidget)
        self.PS_P2Money.setGeometry(QtCore.QRect(248, 570, 150, 25))
        font = QtGui.QFont()
        font.setFamily("Univers 75 Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.PS_P2Money.setFont(font)
        self.PS_P2Money.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.PS_P2Money.setAlignment(QtCore.Qt.AlignCenter)
        self.PS_P2Money.setObjectName("PS_P2Money")
        self.PS_P3Money = QtWidgets.QLabel(self.centralwidget)
        self.PS_P3Money.setGeometry(QtCore.QRect(437, 570, 150, 25))
        font = QtGui.QFont()
        font.setFamily("Univers 75 Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.PS_P3Money.setFont(font)
        self.PS_P3Money.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.PS_P3Money.setAlignment(QtCore.Qt.AlignCenter)
        self.PS_P3Money.setObjectName("PS_P3Money")
        self.PS_P4Money = QtWidgets.QLabel(self.centralwidget)
        self.PS_P4Money.setGeometry(QtCore.QRect(626, 570, 150, 25))
        font = QtGui.QFont()
        font.setFamily("Univers 75 Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.PS_P4Money.setFont(font)
        self.PS_P4Money.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.PS_P4Money.setAlignment(QtCore.Qt.AlignCenter)
        self.PS_P4Money.setObjectName("PS_P4Money")
        self.PS_P5Money = QtWidgets.QLabel(self.centralwidget)
        self.PS_P5Money.setGeometry(QtCore.QRect(815, 570, 150, 25))
        font = QtGui.QFont()
        font.setFamily("Univers 75 Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.PS_P5Money.setFont(font)
        self.PS_P5Money.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.PS_P5Money.setAlignment(QtCore.Qt.AlignCenter)
        self.PS_P5Money.setObjectName("PS_P5Money")
        self.Cat1Clue1B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat1Clue1B.setGeometry(QtCore.QRect(26, 110, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat1Clue1B.setFont(font)
        self.Cat1Clue1B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat1Clue1B.setObjectName("Cat1Clue1B")
        self.Cat3Clue1B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat3Clue1B.setGeometry(QtCore.QRect(352, 110, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat3Clue1B.setFont(font)
        self.Cat3Clue1B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat3Clue1B.setObjectName("Cat3Clue1B")
        self.Cat4Clue1B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat4Clue1B.setGeometry(QtCore.QRect(515, 110, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat4Clue1B.setFont(font)
        self.Cat4Clue1B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat4Clue1B.setObjectName("Cat4Clue1B")
        self.Cat5Clue1B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat5Clue1B.setGeometry(QtCore.QRect(678, 110, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat5Clue1B.setFont(font)
        self.Cat5Clue1B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat5Clue1B.setObjectName("Cat5Clue1B")
        self.Cat6Clue1B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat6Clue1B.setGeometry(QtCore.QRect(841, 110, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat6Clue1B.setFont(font)
        self.Cat6Clue1B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat6Clue1B.setObjectName("Cat6Clue1B")
        self.Cat1Clue2B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat1Clue2B.setGeometry(QtCore.QRect(26, 194, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat1Clue2B.setFont(font)
        self.Cat1Clue2B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat1Clue2B.setObjectName("Cat1Clue2B")
        self.Cat1Clue3B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat1Clue3B.setGeometry(QtCore.QRect(26, 278, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat1Clue3B.setFont(font)
        self.Cat1Clue3B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat1Clue3B.setObjectName("Cat1Clue3B")
        self.Cat1Clue4B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat1Clue4B.setGeometry(QtCore.QRect(26, 362, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat1Clue4B.setFont(font)
        self.Cat1Clue4B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat1Clue4B.setObjectName("Cat1Clue4B")
        self.Cat1Clue5B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat1Clue5B.setGeometry(QtCore.QRect(26, 446, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat1Clue5B.setFont(font)
        self.Cat1Clue5B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat1Clue5B.setObjectName("Cat1Clue5B")
        self.Cat2Clue2B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat2Clue2B.setGeometry(QtCore.QRect(189, 194, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat2Clue2B.setFont(font)
        self.Cat2Clue2B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat2Clue2B.setObjectName("Cat2Clue2B")
        self.Cat5Clue2B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat5Clue2B.setGeometry(QtCore.QRect(678, 194, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat5Clue2B.setFont(font)
        self.Cat5Clue2B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat5Clue2B.setObjectName("Cat5Clue2B")
        self.Cat4Clue2B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat4Clue2B.setGeometry(QtCore.QRect(515, 194, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat4Clue2B.setFont(font)
        self.Cat4Clue2B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat4Clue2B.setObjectName("Cat4Clue2B")
        self.Cat3Clue2B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat3Clue2B.setGeometry(QtCore.QRect(352, 194, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat3Clue2B.setFont(font)
        self.Cat3Clue2B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat3Clue2B.setObjectName("Cat3Clue2B")
        self.Cat2Clue3B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat2Clue3B.setGeometry(QtCore.QRect(189, 278, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat2Clue3B.setFont(font)
        self.Cat2Clue3B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat2Clue3B.setObjectName("Cat2Clue3B")
        self.Cat3Clue3B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat3Clue3B.setGeometry(QtCore.QRect(352, 278, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat3Clue3B.setFont(font)
        self.Cat3Clue3B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat3Clue3B.setObjectName("Cat3Clue3B")
        self.Cat4Clue3B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat4Clue3B.setGeometry(QtCore.QRect(515, 278, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat4Clue3B.setFont(font)
        self.Cat4Clue3B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat4Clue3B.setObjectName("Cat4Clue3B")
        self.Cat6Clue3B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat6Clue3B.setGeometry(QtCore.QRect(841, 278, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat6Clue3B.setFont(font)
        self.Cat6Clue3B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat6Clue3B.setObjectName("Cat6Clue3B")
        self.Cat5Clue3B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat5Clue3B.setGeometry(QtCore.QRect(678, 278, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat5Clue3B.setFont(font)
        self.Cat5Clue3B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat5Clue3B.setObjectName("Cat5Clue3B")
        self.Cat2Clue4B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat2Clue4B.setGeometry(QtCore.QRect(189, 362, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat2Clue4B.setFont(font)
        self.Cat2Clue4B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat2Clue4B.setObjectName("Cat2Clue4B")
        self.Cat5Clue4B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat5Clue4B.setGeometry(QtCore.QRect(678, 362, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat5Clue4B.setFont(font)
        self.Cat5Clue4B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat5Clue4B.setObjectName("Cat5Clue4B")
        self.Cat4Clue4B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat4Clue4B.setGeometry(QtCore.QRect(515, 362, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat4Clue4B.setFont(font)
        self.Cat4Clue4B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat4Clue4B.setObjectName("Cat4Clue4B")
        self.Cat3Clue4B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat3Clue4B.setGeometry(QtCore.QRect(352, 362, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat3Clue4B.setFont(font)
        self.Cat3Clue4B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat3Clue4B.setObjectName("Cat3Clue4B")
        self.Cat6Clue4B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat6Clue4B.setGeometry(QtCore.QRect(841, 362, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat6Clue4B.setFont(font)
        self.Cat6Clue4B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat6Clue4B.setObjectName("Cat6Clue4B")
        self.Cat4Clue5B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat4Clue5B.setGeometry(QtCore.QRect(515, 446, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat4Clue5B.setFont(font)
        self.Cat4Clue5B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat4Clue5B.setObjectName("Cat4Clue5B")
        self.Cat5Clue5B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat5Clue5B.setGeometry(QtCore.QRect(678, 446, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat5Clue5B.setFont(font)
        self.Cat5Clue5B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat5Clue5B.setObjectName("Cat5Clue5B")
        self.Cat6Clue5B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat6Clue5B.setGeometry(QtCore.QRect(841, 446, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat6Clue5B.setFont(font)
        self.Cat6Clue5B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat6Clue5B.setObjectName("Cat6Clue5B")
        self.Cat3Clue5B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat3Clue5B.setGeometry(QtCore.QRect(352, 446, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat3Clue5B.setFont(font)
        self.Cat3Clue5B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat3Clue5B.setObjectName("Cat3Clue5B")
        self.Cat2Clue5B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat2Clue5B.setGeometry(QtCore.QRect(189, 446, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat2Clue5B.setFont(font)
        self.Cat2Clue5B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat2Clue5B.setObjectName("Cat2Clue5B")
        self.Cat6Clue2B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat6Clue2B.setGeometry(QtCore.QRect(841, 194, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat6Clue2B.setFont(font)
        self.Cat6Clue2B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat6Clue2B.setObjectName("Cat6Clue2B")
        self.CloseButton = QtWidgets.QPushButton(self.centralwidget)
        self.CloseButton.setGeometry(QtCore.QRect(1764, 10, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.CloseButton.setFont(font)
        self.CloseButton.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.CloseButton.setObjectName("CloseButton")
        self.AS_P5Name = QtWidgets.QLabel(self.centralwidget)
        self.AS_P5Name.setGeometry(QtCore.QRect(1029, 425, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AS_P5Name.setFont(font)
        self.AS_P5Name.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.AS_P5Name.setAlignment(QtCore.Qt.AlignCenter)
        self.AS_P5Name.setObjectName("AS_P5Name")
        self.AS_DecoLabel = QtWidgets.QLabel(self.centralwidget)
        self.AS_DecoLabel.setGeometry(QtCore.QRect(1024, 420, 800, 60))
        self.AS_DecoLabel.setStyleSheet("background-color: #060CE9;")
        self.AS_DecoLabel.setText("")
        self.AS_DecoLabel.setObjectName("AS_DecoLabel")
        self.AS_P4Name = QtWidgets.QLabel(self.centralwidget)
        self.AS_P4Name.setGeometry(QtCore.QRect(1189, 425, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AS_P4Name.setFont(font)
        self.AS_P4Name.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.AS_P4Name.setAlignment(QtCore.Qt.AlignCenter)
        self.AS_P4Name.setObjectName("AS_P4Name")
        self.AS_P3Name = QtWidgets.QLabel(self.centralwidget)
        self.AS_P3Name.setGeometry(QtCore.QRect(1349, 425, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AS_P3Name.setFont(font)
        self.AS_P3Name.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.AS_P3Name.setAlignment(QtCore.Qt.AlignCenter)
        self.AS_P3Name.setObjectName("AS_P3Name")
        self.AS_P2Name = QtWidgets.QLabel(self.centralwidget)
        self.AS_P2Name.setGeometry(QtCore.QRect(1509, 425, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AS_P2Name.setFont(font)
        self.AS_P2Name.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.AS_P2Name.setAlignment(QtCore.Qt.AlignCenter)
        self.AS_P2Name.setObjectName("AS_P2Name")
        self.AS_P1Name = QtWidgets.QLabel(self.centralwidget)
        self.AS_P1Name.setGeometry(QtCore.QRect(1669, 425, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AS_P1Name.setFont(font)
        self.AS_P1Name.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.AS_P1Name.setAlignment(QtCore.Qt.AlignCenter)
        self.AS_P1Name.setObjectName("AS_P1Name")
        self.AS_P5Money = QtWidgets.QLabel(self.centralwidget)
        self.AS_P5Money.setGeometry(QtCore.QRect(1029, 450, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AS_P5Money.setFont(font)
        self.AS_P5Money.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.AS_P5Money.setAlignment(QtCore.Qt.AlignCenter)
        self.AS_P5Money.setObjectName("AS_P5Money")
        self.AS_P4Money = QtWidgets.QLabel(self.centralwidget)
        self.AS_P4Money.setGeometry(QtCore.QRect(1189, 450, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AS_P4Money.setFont(font)
        self.AS_P4Money.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.AS_P4Money.setAlignment(QtCore.Qt.AlignCenter)
        self.AS_P4Money.setObjectName("AS_P4Money")
        self.AS_P3Money = QtWidgets.QLabel(self.centralwidget)
        self.AS_P3Money.setGeometry(QtCore.QRect(1349, 450, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AS_P3Money.setFont(font)
        self.AS_P3Money.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.AS_P3Money.setAlignment(QtCore.Qt.AlignCenter)
        self.AS_P3Money.setObjectName("AS_P3Money")
        self.AS_P2Money = QtWidgets.QLabel(self.centralwidget)
        self.AS_P2Money.setGeometry(QtCore.QRect(1509, 450, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AS_P2Money.setFont(font)
        self.AS_P2Money.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.AS_P2Money.setAlignment(QtCore.Qt.AlignCenter)
        self.AS_P2Money.setObjectName("AS_P2Money")
        self.AS_P1Money = QtWidgets.QLabel(self.centralwidget)
        self.AS_P1Money.setGeometry(QtCore.QRect(1669, 450, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AS_P1Money.setFont(font)
        self.AS_P1Money.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.AS_P1Money.setAlignment(QtCore.Qt.AlignCenter)
        self.AS_P1Money.setObjectName("AS_P1Money")
        self.CatLabel1 = QtWidgets.QLabel(self.centralwidget)
        self.CatLabel1.setGeometry(QtCore.QRect(26, 16, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(14)
        self.CatLabel1.setFont(font)
        self.CatLabel1.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.CatLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.CatLabel1.setObjectName("CatLabel1")
        self.CatLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.CatLabel2.setGeometry(QtCore.QRect(189, 16, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(14)
        self.CatLabel2.setFont(font)
        self.CatLabel2.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.CatLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.CatLabel2.setObjectName("CatLabel2")
        self.CatLabel3 = QtWidgets.QLabel(self.centralwidget)
        self.CatLabel3.setGeometry(QtCore.QRect(352, 16, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(14)
        self.CatLabel3.setFont(font)
        self.CatLabel3.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.CatLabel3.setAlignment(QtCore.Qt.AlignCenter)
        self.CatLabel3.setObjectName("CatLabel3")
        self.CatLabel4 = QtWidgets.QLabel(self.centralwidget)
        self.CatLabel4.setGeometry(QtCore.QRect(515, 16, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(14)
        self.CatLabel4.setFont(font)
        self.CatLabel4.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.CatLabel4.setAlignment(QtCore.Qt.AlignCenter)
        self.CatLabel4.setObjectName("CatLabel4")
        self.CatLabel5 = QtWidgets.QLabel(self.centralwidget)
        self.CatLabel5.setGeometry(QtCore.QRect(678, 16, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(14)
        self.CatLabel5.setFont(font)
        self.CatLabel5.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.CatLabel5.setAlignment(QtCore.Qt.AlignCenter)
        self.CatLabel5.setObjectName("CatLabel5")
        self.CatLabel6 = QtWidgets.QLabel(self.centralwidget)
        self.CatLabel6.setGeometry(QtCore.QRect(841, 16, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(14)
        self.CatLabel6.setFont(font)
        self.CatLabel6.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.CatLabel6.setAlignment(QtCore.Qt.AlignCenter)
        self.CatLabel6.setObjectName("CatLabel6")
        self.Cat1Button = QtWidgets.QPushButton(self.centralwidget)
        self.Cat1Button.setGeometry(QtCore.QRect(26, 16, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.Cat1Button.setFont(font)
        self.Cat1Button.setStyleSheet("QPushButton { background-color: transparent; border: 0px }\n"
"")
        self.Cat1Button.setText("")
        self.Cat1Button.setObjectName("Cat1Button")
        self.Cat2Clue1B = QtWidgets.QPushButton(self.centralwidget)
        self.Cat2Clue1B.setGeometry(QtCore.QRect(189, 110, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Cat2Clue1B.setFont(font)
        self.Cat2Clue1B.setStyleSheet("QPushButton { background-color: #060CE9; border: 0px; color: #d69f4c;}")
        self.Cat2Clue1B.setObjectName("Cat2Clue1B")
        self.Cat2Button = QtWidgets.QPushButton(self.centralwidget)
        self.Cat2Button.setGeometry(QtCore.QRect(189, 16, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.Cat2Button.setFont(font)
        self.Cat2Button.setStyleSheet("QPushButton { background-color: transparent; border: 0px }")
        self.Cat2Button.setText("")
        self.Cat2Button.setObjectName("Cat2Button")
        self.Cat3Button = QtWidgets.QPushButton(self.centralwidget)
        self.Cat3Button.setGeometry(QtCore.QRect(352, 16, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.Cat3Button.setFont(font)
        self.Cat3Button.setStyleSheet("QPushButton { background-color: transparent; border: 0px }")
        self.Cat3Button.setText("")
        self.Cat3Button.setObjectName("Cat3Button")
        self.Cat4Button = QtWidgets.QPushButton(self.centralwidget)
        self.Cat4Button.setGeometry(QtCore.QRect(515, 16, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.Cat4Button.setFont(font)
        self.Cat4Button.setStyleSheet("QPushButton { background-color: transparent; border: 0px }")
        self.Cat4Button.setText("")
        self.Cat4Button.setObjectName("Cat4Button")
        self.Cat5Button = QtWidgets.QPushButton(self.centralwidget)
        self.Cat5Button.setGeometry(QtCore.QRect(678, 16, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.Cat5Button.setFont(font)
        self.Cat5Button.setStyleSheet("QPushButton { background-color: transparent; border: 0px }")
        self.Cat5Button.setText("")
        self.Cat5Button.setObjectName("Cat5Button")
        self.Cat6Button = QtWidgets.QPushButton(self.centralwidget)
        self.Cat6Button.setGeometry(QtCore.QRect(841, 16, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.Cat6Button.setFont(font)
        self.Cat6Button.setStyleSheet("QPushButton { background-color: transparent; border: 0px }")
        self.Cat6Button.setText("")
        self.Cat6Button.setObjectName("Cat6Button")
        self.CatLabel4.raise_()
        self.CatLabel3.raise_()
        self.CatLabel2.raise_()
        self.CatLabel1.raise_()
        self.CatLabel6.raise_()
        self.AS_DecoLabel.raise_()
        self.ReadyIndicatorR.raise_()
        self.ReadyIndicatorL.raise_()
        self.PS_DecoLabel.raise_()
        self.PS_P1Name.raise_()
        self.PS_P1Money.raise_()
        self.PS_P2Name.raise_()
        self.PS_P3Name.raise_()
        self.PS_P4Name.raise_()
        self.PS_P5Name.raise_()
        self.PS_P2Money.raise_()
        self.PS_P3Money.raise_()
        self.PS_P4Money.raise_()
        self.PS_P5Money.raise_()
        self.Cat1Clue1B.raise_()
        self.Cat3Clue1B.raise_()
        self.Cat4Clue1B.raise_()
        self.Cat5Clue1B.raise_()
        self.Cat6Clue1B.raise_()
        self.Cat1Clue2B.raise_()
        self.Cat1Clue3B.raise_()
        self.Cat1Clue4B.raise_()
        self.Cat1Clue5B.raise_()
        self.Cat2Clue2B.raise_()
        self.Cat5Clue2B.raise_()
        self.Cat4Clue2B.raise_()
        self.Cat3Clue2B.raise_()
        self.Cat2Clue3B.raise_()
        self.Cat3Clue3B.raise_()
        self.Cat4Clue3B.raise_()
        self.Cat6Clue3B.raise_()
        self.Cat5Clue3B.raise_()
        self.Cat2Clue4B.raise_()
        self.Cat5Clue4B.raise_()
        self.Cat4Clue4B.raise_()
        self.Cat3Clue4B.raise_()
        self.Cat6Clue4B.raise_()
        self.Cat4Clue5B.raise_()
        self.Cat5Clue5B.raise_()
        self.Cat6Clue5B.raise_()
        self.Cat3Clue5B.raise_()
        self.Cat2Clue5B.raise_()
        self.Cat6Clue2B.raise_()
        self.CloseButton.raise_()
        self.AS_P5Name.raise_()
        self.AS_P4Name.raise_()
        self.AS_P3Name.raise_()
        self.AS_P2Name.raise_()
        self.AS_P1Name.raise_()
        self.AS_P5Money.raise_()
        self.AS_P4Money.raise_()
        self.AS_P3Money.raise_()
        self.AS_P2Money.raise_()
        self.AS_P1Money.raise_()
        self.CatLabel5.raise_()
        self.Cat1Button.raise_()
        self.Cat2Clue1B.raise_()
        self.Cat2Button.raise_()
        self.Cat3Button.raise_()
        self.Cat4Button.raise_()
        self.Cat5Button.raise_()
        self.Cat6Button.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


###########################################################################################################
##################################### Button Connects #####################################
###########################################################################################################
        self.CloseButton.clicked.connect(self.closeButtonPressed)

        # lambda is used to send the category and clue as parameters so that they can all
        # call the same function, but we can differentiate between them to display the 
        # correct clue
        self.Cat1Clue1B.clicked.connect(lambda: self.showClueWindow(category = 1, clue = 1, amount = 200*gameRound, dailyDouble=df.iloc[cat1Index+0, 2]))
        self.Cat1Clue2B.clicked.connect(lambda: self.showClueWindow(category = 1, clue = 2, amount = 400*gameRound, dailyDouble=df.iloc[cat1Index+1, 2]))
        self.Cat1Clue3B.clicked.connect(lambda: self.showClueWindow(category = 1, clue = 3, amount = 600*gameRound, dailyDouble=df.iloc[cat1Index+2, 2]))
        self.Cat1Clue4B.clicked.connect(lambda: self.showClueWindow(category = 1, clue = 4, amount = 800*gameRound, dailyDouble=df.iloc[cat1Index+3, 2]))
        self.Cat1Clue5B.clicked.connect(lambda: self.showClueWindow(category = 1, clue = 5, amount = 1000*gameRound, dailyDouble=df.iloc[cat1Index+4, 2]))
        self.Cat2Clue1B.clicked.connect(lambda: self.showClueWindow(category = 2, clue = 1, amount = 200*gameRound, dailyDouble=df.iloc[cat2Index+0, 2]))
        self.Cat2Clue2B.clicked.connect(lambda: self.showClueWindow(category = 2, clue = 2, amount = 400*gameRound, dailyDouble=df.iloc[cat2Index+1, 2]))
        self.Cat2Clue3B.clicked.connect(lambda: self.showClueWindow(category = 2, clue = 3, amount = 600*gameRound, dailyDouble=df.iloc[cat2Index+2, 2]))
        self.Cat2Clue4B.clicked.connect(lambda: self.showClueWindow(category = 2, clue = 4, amount = 800*gameRound, dailyDouble=df.iloc[cat2Index+3, 2]))
        self.Cat2Clue5B.clicked.connect(lambda: self.showClueWindow(category = 2, clue = 5, amount = 1000*gameRound, dailyDouble=df.iloc[cat2Index+4, 2]))
        self.Cat3Clue1B.clicked.connect(lambda: self.showClueWindow(category = 3, clue = 1, amount = 200*gameRound, dailyDouble=df.iloc[cat3Index+0, 2]))
        self.Cat3Clue2B.clicked.connect(lambda: self.showClueWindow(category = 3, clue = 2, amount = 400*gameRound, dailyDouble=df.iloc[cat3Index+1, 2]))
        self.Cat3Clue3B.clicked.connect(lambda: self.showClueWindow(category = 3, clue = 3, amount = 600*gameRound, dailyDouble=df.iloc[cat3Index+2, 2]))
        self.Cat3Clue4B.clicked.connect(lambda: self.showClueWindow(category = 3, clue = 4, amount = 800*gameRound, dailyDouble=df.iloc[cat3Index+3, 2]))
        self.Cat3Clue5B.clicked.connect(lambda: self.showClueWindow(category = 3, clue = 5, amount = 1000*gameRound, dailyDouble=df.iloc[cat3Index+4, 2]))
        self.Cat4Clue1B.clicked.connect(lambda: self.showClueWindow(category = 4, clue = 1, amount = 200*gameRound, dailyDouble=df.iloc[cat4Index+0, 2]))
        self.Cat4Clue2B.clicked.connect(lambda: self.showClueWindow(category = 4, clue = 2, amount = 400*gameRound, dailyDouble=df.iloc[cat4Index+1, 2]))
        self.Cat4Clue3B.clicked.connect(lambda: self.showClueWindow(category = 4, clue = 3, amount = 600*gameRound, dailyDouble=df.iloc[cat4Index+2, 2]))
        self.Cat4Clue4B.clicked.connect(lambda: self.showClueWindow(category = 4, clue = 4, amount = 800*gameRound, dailyDouble=df.iloc[cat4Index+3, 2]))
        self.Cat4Clue5B.clicked.connect(lambda: self.showClueWindow(category = 4, clue = 5, amount = 1000*gameRound, dailyDouble=df.iloc[cat4Index+4, 2]))
        self.Cat5Clue1B.clicked.connect(lambda: self.showClueWindow(category = 5, clue = 1, amount = 200*gameRound, dailyDouble=df.iloc[cat5Index+0, 2]))
        self.Cat5Clue2B.clicked.connect(lambda: self.showClueWindow(category = 5, clue = 2, amount = 400*gameRound, dailyDouble=df.iloc[cat5Index+1, 2]))
        self.Cat5Clue3B.clicked.connect(lambda: self.showClueWindow(category = 5, clue = 3, amount = 600*gameRound, dailyDouble=df.iloc[cat5Index+2, 2]))
        self.Cat5Clue4B.clicked.connect(lambda: self.showClueWindow(category = 5, clue = 4, amount = 800*gameRound, dailyDouble=df.iloc[cat5Index+3, 2]))
        self.Cat5Clue5B.clicked.connect(lambda: self.showClueWindow(category = 5, clue = 5, amount = 1000*gameRound, dailyDouble=df.iloc[cat5Index+4, 2]))
        self.Cat6Clue1B.clicked.connect(lambda: self.showClueWindow(category = 6, clue = 1, amount = 200*gameRound, dailyDouble=df.iloc[cat6Index+0, 2]))
        self.Cat6Clue2B.clicked.connect(lambda: self.showClueWindow(category = 6, clue = 2, amount = 400*gameRound, dailyDouble=df.iloc[cat6Index+1, 2]))
        self.Cat6Clue3B.clicked.connect(lambda: self.showClueWindow(category = 6, clue = 3, amount = 600*gameRound, dailyDouble=df.iloc[cat6Index+2, 2]))
        self.Cat6Clue4B.clicked.connect(lambda: self.showClueWindow(category = 6, clue = 4, amount = 800*gameRound, dailyDouble=df.iloc[cat6Index+3, 2]))
        self.Cat6Clue5B.clicked.connect(lambda: self.showClueWindow(category = 6, clue = 5, amount = 1000*gameRound, dailyDouble=df.iloc[cat6Index+4, 2]))

        

    def retranslateUi(self, MainWindow):
        GPIO.setmode(GPIO.BCM)
        GPIO.setup(23, GPIO.IN, pull_up_down=GPIO.PUD_UP) #player1 buzzer
        GPIO.setup(24, GPIO.IN, pull_up_down=GPIO.PUD_UP) #player2 buzzer
        GPIO.setup(25, GPIO.IN, pull_up_down=GPIO.PUD_UP) #player3 buzzer
        GPIO.setup(8, GPIO.IN, pull_up_down=GPIO.PUD_UP) #player4 buzzer
        GPIO.setup(7, GPIO.IN, pull_up_down=GPIO.PUD_UP) #player5 buzzer
        GPIO.setup(12, GPIO.IN, pull_up_down=GPIO.PUD_UP) #alex buzzer

        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PS_P1Name.setText(_translate("MainWindow", "Player1"))
        self.PS_P1Money.setText(_translate("MainWindow", "$0"))
        self.PS_P2Name.setText(_translate("MainWindow", "Player2"))
        self.PS_P3Name.setText(_translate("MainWindow", "Player3"))
        self.PS_P4Name.setText(_translate("MainWindow", "Player4"))
        self.PS_P5Name.setText(_translate("MainWindow", "Player5"))
        self.PS_P2Money.setText(_translate("MainWindow", "$0"))
        self.PS_P3Money.setText(_translate("MainWindow", "$0"))
        self.PS_P4Money.setText(_translate("MainWindow", "$0"))
        self.PS_P5Money.setText(_translate("MainWindow", "$0"))
        self.Cat1Clue1B.setText(_translate("MainWindow", "$200"))
        self.Cat3Clue1B.setText(_translate("MainWindow", "$200"))
        self.Cat4Clue1B.setText(_translate("MainWindow", "$200"))
        self.Cat5Clue1B.setText(_translate("MainWindow", "$200"))
        self.Cat6Clue1B.setText(_translate("MainWindow", "$200"))
        self.Cat1Clue2B.setText(_translate("MainWindow", "$400"))
        self.Cat1Clue3B.setText(_translate("MainWindow", "$600"))
        self.Cat1Clue4B.setText(_translate("MainWindow", "$800"))
        self.Cat1Clue5B.setText(_translate("MainWindow", "$1000"))
        self.Cat2Clue2B.setText(_translate("MainWindow", "$400"))
        self.Cat5Clue2B.setText(_translate("MainWindow", "$400"))
        self.Cat4Clue2B.setText(_translate("MainWindow", "$400"))
        self.Cat3Clue2B.setText(_translate("MainWindow", "$400"))
        self.Cat2Clue3B.setText(_translate("MainWindow", "$600"))
        self.Cat3Clue3B.setText(_translate("MainWindow", "$600"))
        self.Cat4Clue3B.setText(_translate("MainWindow", "$600"))
        self.Cat6Clue3B.setText(_translate("MainWindow", "$600"))
        self.Cat5Clue3B.setText(_translate("MainWindow", "$600"))
        self.Cat2Clue4B.setText(_translate("MainWindow", "$800"))
        self.Cat5Clue4B.setText(_translate("MainWindow", "$800"))
        self.Cat4Clue4B.setText(_translate("MainWindow", "$800"))
        self.Cat3Clue4B.setText(_translate("MainWindow", "$800"))
        self.Cat6Clue4B.setText(_translate("MainWindow", "$800"))
        self.Cat4Clue5B.setText(_translate("MainWindow", "$1000"))
        self.Cat5Clue5B.setText(_translate("MainWindow", "$1000"))
        self.Cat6Clue5B.setText(_translate("MainWindow", "$1000"))
        self.Cat3Clue5B.setText(_translate("MainWindow", "$1000"))
        self.Cat2Clue5B.setText(_translate("MainWindow", "$1000"))
        self.Cat6Clue2B.setText(_translate("MainWindow", "$400"))
        self.CloseButton.setText(_translate("MainWindow", "X"))
        self.AS_P5Name.setText(_translate("MainWindow", "Player5"))
        self.AS_P4Name.setText(_translate("MainWindow", "Player4"))
        self.AS_P3Name.setText(_translate("MainWindow", "Player3"))
        self.AS_P2Name.setText(_translate("MainWindow", "Player2"))
        self.AS_P1Name.setText(_translate("MainWindow", "Player1"))
        self.AS_P5Money.setText(_translate("MainWindow", "$0"))
        self.AS_P4Money.setText(_translate("MainWindow", "$0"))
        self.AS_P3Money.setText(_translate("MainWindow", "$0"))
        self.AS_P2Money.setText(_translate("MainWindow", "$0"))
        self.AS_P1Money.setText(_translate("MainWindow", "$0"))
        self.CatLabel1.setText(_translate("MainWindow", "Cat1"))
        self.CatLabel2.setText(_translate("MainWindow", "Cat2"))
        self.CatLabel3.setText(_translate("MainWindow", "Cat3"))
        self.CatLabel4.setText(_translate("MainWindow", "Cat4"))
        self.CatLabel5.setText(_translate("MainWindow", "Cat5"))
        self.CatLabel6.setText(_translate("MainWindow", "Cat6"))
        self.Cat2Clue1B.setText(_translate("MainWindow", "$200"))

        self.CatLabel1.setWordWrap(True)
        self.CatLabel2.setWordWrap(True)
        self.CatLabel3.setWordWrap(True)
        self.CatLabel4.setWordWrap(True)
        self.CatLabel5.setWordWrap(True)
        self.CatLabel6.setWordWrap(True)


if __name__ == "__main__":
    initCluesAndCats(gameRound)

    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    
    #TODO: I set bouncetime=1, but I'm not 100% sure that's okay
    GPIO.add_event_detect(23, GPIO.FALLING, callback=ui.playerBuzzerPressed, bouncetime=1)
    GPIO.add_event_detect(24, GPIO.FALLING, callback=ui.playerBuzzerPressed, bouncetime=1)
    GPIO.add_event_detect(25, GPIO.FALLING, callback=ui.playerBuzzerPressed, bouncetime=1)
    GPIO.add_event_detect(8, GPIO.FALLING, callback=ui.playerBuzzerPressed, bouncetime=1)
    GPIO.add_event_detect(7, GPIO.FALLING, callback=ui.playerBuzzerPressed, bouncetime=1)
        #alex's button has bouncetime bc it's both rising and falling edge that matters
    GPIO.add_event_detect(12, GPIO.BOTH, callback=ui.alexBuzzerPressedOrReleased, bouncetime=50)

    MainWindow.setWindowFlag(Qt.FramelessWindowHint)
    MainWindow.show()
    ui.setCategories()
    sys.exit(app.exec_())
