# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BasicAlexClueWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 200)
        Form.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.clueLabel = QtWidgets.QLabel(Form)
        self.clueLabel.setGeometry(QtCore.QRect(80, 0, 641, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.clueLabel.setFont(font)
        self.clueLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.clueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.clueLabel.setObjectName("clueLabel")
        self.responseLabel = QtWidgets.QLabel(Form)
        self.responseLabel.setGeometry(QtCore.QRect(150, 110, 521, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.responseLabel.setFont(font)
        self.responseLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.responseLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.responseLabel.setObjectName("responseLabel")
        self.correctButton = QtWidgets.QPushButton(Form)
        self.correctButton.setGeometry(QtCore.QRect(170, 160, 211, 31))
        self.correctButton.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.correctButton.setObjectName("correctButton")
        self.incorrectButton = QtWidgets.QPushButton(Form)
        self.incorrectButton.setGeometry(QtCore.QRect(420, 160, 211, 31))
        self.incorrectButton.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.incorrectButton.setObjectName("incorrectButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.clueLabel.setText(_translate("Form", "Test text: this is where the prompt goes"))
        self.responseLabel.setText(_translate("Form", "Test text: this is where the response goes"))
        self.correctButton.setText(_translate("Form", "Correct"))
        self.incorrectButton.setText(_translate("Form", "Incorrect"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.setWindowFlag(Qt.FramelessWindowHint)
    Form.show()
    sys.exit(app.exec_())
