# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BasicAlexClueMM.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import * 
from PyQt5.QtWidgets import * 


class Ui_BasicAlexClueMM(object):
    def setupUi(self, BasicAlexClueMM):
        BasicAlexClueMM.setObjectName("BasicAlexClueMM")
        #BasicAlexClueMM.resize(800, 250)
        BasicAlexClueMM.setGeometry(1024, 100, 800, 250)
        BasicAlexClueMM.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(BasicAlexClueMM)
        self.centralwidget.setObjectName("centralwidget")
        self.alexClueLabel = QtWidgets.QLabel(self.centralwidget)
        self.alexClueLabel.setGeometry(QtCore.QRect(100, -20, 611, 101))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.alexClueLabel.setFont(font)
        self.alexClueLabel.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.alexClueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.alexClueLabel.setObjectName("alexClueLabel")
        self.alexResponseLabel = QtWidgets.QLabel(self.centralwidget)
        self.alexResponseLabel.setGeometry(QtCore.QRect(100, 80, 611, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.alexResponseLabel.setFont(font)
        self.alexResponseLabel.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.alexResponseLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.alexResponseLabel.setObjectName("alexResponseLabel")
        self.correctButton = QtWidgets.QPushButton(self.centralwidget)
        self.correctButton.setGeometry(QtCore.QRect(100, 140, 291, 41))
        self.correctButton.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.correctButton.setObjectName("correctButton")
        self.incorrectButton = QtWidgets.QPushButton(self.centralwidget)
        self.incorrectButton.setGeometry(QtCore.QRect(420, 140, 291, 41))
        self.incorrectButton.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.incorrectButton.setObjectName("incorrectButton")
        BasicAlexClueMM.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BasicAlexClueMM)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        BasicAlexClueMM.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BasicAlexClueMM)
        self.statusbar.setObjectName("statusbar")
        BasicAlexClueMM.setStatusBar(self.statusbar)

        self.retranslateUi(BasicAlexClueMM)
        QtCore.QMetaObject.connectSlotsByName(BasicAlexClueMM)

    def retranslateUi(self, BasicAlexClueMM):
        _translate = QtCore.QCoreApplication.translate
        BasicAlexClueMM.setWindowTitle(_translate("BasicAlexClueMM", "MainWindow"))
        self.alexClueLabel.setText(_translate("BasicAlexClueMM", "Testtext: clue goes here"))
        self.alexResponseLabel.setText(_translate("BasicAlexClueMM", "Testtext: response goes here"))
        self.correctButton.setText(_translate("BasicAlexClueMM", "Correct"))
        self.incorrectButton.setText(_translate("BasicAlexClueMM", "Incorrect"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BasicAlexClueMM = QtWidgets.QMainWindow()
    ui = Ui_BasicAlexClueMM()
    ui.setupUi(BasicAlexClueMM)
    BasicAlexClueMM.show()
    sys.exit(app.exec_())
