# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CompleteButUglyPrompt.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Promp_Widget(object):
    def setupUi(self, Promp_Widget):
        Promp_Widget.setObjectName("Promp_Widget")
        Promp_Widget.resize(400, 300)
        Promp_Widget.setStyleSheet("background-color: black;")
        self.clue = QtWidgets.QLabel(Promp_Widget)
        self.clue.setGeometry(QtCore.QRect(10, 10, 381, 201))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.clue.setFont(font)
        self.clue.setStyleSheet("color: white;\n"
"background-color: #060CE9;\n"
"\n"
"")
        self.clue.setAlignment(QtCore.Qt.AlignCenter)
        self.clue.setObjectName("clue")
        self.pushButton = QtWidgets.QPushButton(Promp_Widget)
        self.pushButton.setGeometry(QtCore.QRect(10, 220, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:red;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Promp_Widget)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 220, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: green;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Promp_Widget)
        QtCore.QMetaObject.connectSlotsByName(Promp_Widget)

    def retranslateUi(self, Promp_Widget):
        _translate = QtCore.QCoreApplication.translate
        Promp_Widget.setWindowTitle(_translate("Promp_Widget", "Dialog"))
        self.clue.setText(_translate("Promp_Widget", "TextLabel"))
        self.pushButton.setText(_translate("Promp_Widget", "Incorrect"))
        self.pushButton_2.setText(_translate("Promp_Widget", "Correct"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Promp_Widget = QtWidgets.QDialog()
    ui = Ui_Promp_Widget()
    ui.setupUi(Promp_Widget)
    Promp_Widget.show()
    sys.exit(app.exec_())
