# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FinalJWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont, QFontDatabase
from FinalJWagersWindow1 import Ui_FinalJWagersWindow
from PyQt5.QtCore import QTimer
from PyQt5.QtWidgets import * 
from PyQt5.QtGui import * 
from PyQt5.QtCore import Qt

player1Score = 0
player2Score = 13876
player3Score = 3800
player4Score = 20000
player5Score = 542

wagerAmount = ""
scoresArray = [(player1Score, "Player1"), (player2Score, "Player2"), (player3Score, "Player3"), (player4Score, "Player4"), (player5Score, "Player5")]
index = 0


class Ui_FinalJWindow(object):
    #TODO: I'm probably not supposed to use exec() this much but i really love it and idk how else to do this. 
    #I am bad at programming, but it's working so far
    #this is to update player scores on a given screen so you don't have these huge blocks everytime you want to show a new screen
    def setScores(self, ui):
        #TODO: could be done with for loop (at leat the first part)
          exec(f'{ui}.AS_P1Name.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
          exec(f'{ui}.AS_P2Name.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
          exec(f'{ui}.AS_P3Name.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
          exec(f'{ui}.AS_P4Name.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
          exec(f'{ui}.AS_P5Name.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
          exec(f'{ui}.PS_P1Name.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
          exec(f'{ui}.PS_P2Name.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
          exec(f'{ui}.PS_P3Name.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
          exec(f'{ui}.PS_P4Name.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
          exec(f'{ui}.PS_P5Name.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
          exec(f'{ui}.AS_P1Name.setText("Player1")')
          exec(f'{ui}.AS_P2Name.setText("Player2")')
          exec(f'{ui}.AS_P3Name.setText("Player3")')
          exec(f'{ui}.AS_P4Name.setText("Player4")')
          exec(f'{ui}.AS_P5Name.setText("Player5")')
          exec(f'{ui}.PS_P1Name.setText("Player1")')
          exec(f'{ui}.PS_P2Name.setText("Player2")')
          exec(f'{ui}.PS_P3Name.setText("Player3")')
          exec(f'{ui}.PS_P4Name.setText("Player4")')
          exec(f'{ui}.PS_P5Name.setText("Player5")')
          if player1Score < 0:
                exec(f'{ui}.PS_P1Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 0, 0);")')
                exec(f'{ui}.PS_P1Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 0, 0);")')
                exec(f'{ui}.AS_P1Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 0, 0);")')
                exec(f'{ui}.PS_P1Money.setText("-$" + str(player1Score)[1:])')
                exec(f'{ui}.AS_P1Money.setText("-$" + str(player1Score)[1:])')
          else:
                exec(f'{ui}.PS_P1Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
                exec(f'{ui}.AS_P1Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
                exec(f'{ui}.PS_P1Money.setText("$" + str(player1Score))')
                exec(f'{ui}.AS_P1Money.setText("$" + str(player1Score))')
          if player2Score < 0:
                exec(f'{ui}.PS_P2Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 0, 0);")')
                exec(f'{ui}.AS_P2Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 0, 0);")')
                exec(f'{ui}.PS_P2Money.setText("-$" + str(player2Score)[1:])')
                exec(f'{ui}.AS_P2Money.setText("-$" + str(player2Score)[1:])')
          else:
                exec(f'{ui}.PS_P2Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
                exec(f'{ui}.AS_P2Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
                exec(f'{ui}.PS_P2Money.setText("$" + str(player2Score))')
                exec(f'{ui}.AS_P2Money.setText("$" + str(player2Score))')
          if player3Score < 0:
                exec(f'{ui}.PS_P3Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 0, 0);")')
                exec(f'{ui}.AS_P3Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 0, 0);")')
                exec(f'{ui}.PS_P3Money.setText("-$" + str(player3Score)[1:])')
                exec(f'{ui}.AS_P3Money.setText("-$" + str(player3Score)[1:])')
          else:
                exec(f'{ui}.PS_P3Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
                exec(f'{ui}.AS_P3Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
                exec(f'{ui}.PS_P3Money.setText("$" + str(player3Score))')
                exec(f'{ui}.AS_P3Money.setText("$" + str(player3Score))')
          if player4Score < 0:
                exec(f'{ui}.PS_P4Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 0, 0);")')
                exec(f'{ui}.AS_P4Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 0, 0);")')
                exec(f'{ui}.PS_P4Money.setText("-$" + str(player4Score)[1:])')
                exec(f'{ui}.AS_P4Money.setText("-$" + str(player4Score)[1:])')
          else:
                exec(f'{ui}.PS_P4Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
                exec(f'{ui}.AS_P4Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
                exec(f'{ui}.PS_P4Money.setText("$" + str(player4Score))')
                exec(f'{ui}.AS_P4Money.setText("$" + str(player4Score))')
          if player5Score < 0:
                exec(f'{ui}.PS_P5Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 0, 0);")')
                exec(f'{ui}.AS_P5Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 0, 0);")')
                exec(f'{ui}.PS_P5Money.setText("-$" + str(player5Score)[1:])')
                exec(f'{ui}.AS_P5Money.setText("-$" + str(player5Score)[1:])')
          else:
                exec(f'{ui}.PS_P5Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
                exec(f'{ui}.AS_P5Money.setStyleSheet("background-color: #060CE9; color: rgb(255, 255, 255);")')
                exec(f'{ui}.PS_P5Money.setText("$" + str(player5Score))')
                exec(f'{ui}.AS_P5Money.setText("$" + str(player5Score))')

        #TODO: this is written really poorly
    def correctOrIncorrect(self, correct):
         global player1Score
         global player2Score
         global player3Score
         global player4Score
         global player5Score
         global index
         global wagerAmount
         global scoresArray
         
         if correct:
                if scoresArray[index][1] == "Player1":
                        player1Score = player1Score + int(wagerAmount)
                if scoresArray[index][1] == "Player2":
                        player2Score = player2Score + int(wagerAmount)
                if scoresArray[index][1] == "Player3":
                        player3Score = player3Score + int(wagerAmount)
                if scoresArray[index][1] == "Player4":
                        player4Score = player4Score + int(wagerAmount)
                if scoresArray[index][1] == "Player5":
                        player5Score = player5Score + int(wagerAmount)
         else:
                if scoresArray[index][1] == "Player1":
                        player1Score = player1Score - int(wagerAmount)
                if scoresArray[index][1] == "Player2":
                        player2Score = player2Score - int(wagerAmount)
                if scoresArray[index][1] == "Player3":
                        player3Score = player3Score - int(wagerAmount)
                if scoresArray[index][1] == "Player4":
                        player4Score = player4Score - int(wagerAmount)
                if scoresArray[index][1] == "Player5":
                        player5Score = player5Score - int(wagerAmount)
                
         self.setScores("self.FinalJWagersWindowui")

         index = index + 1
         wagerAmount = ""

         if index == len(scoresArray):
                self.FinalJWagersWindowui.correctButton.setVisible(False)
                self.FinalJWagersWindowui.incorrectButton.setVisible(False)
                scoresArray = [(player1Score, "Player1"), (player2Score, "Player2"), (player3Score, "Player3"), (player4Score, "Player4"), (player5Score, "Player5")]
                scoresArray = sorted(scoresArray, key=lambda x: x[0])
                self.FinalJWagersWindowui.ReponseLabel.setText(scoresArray[4][1] + " is the winner!")
                self.FinalJWagersWindowui.PS_ClueLabel.setText(scoresArray[4][1] + " is the winner!")
         else:
                self.FinalJWagersWindowui.button0.setVisible(True)
                self.FinalJWagersWindowui.button1.setVisible(True)
                self.FinalJWagersWindowui.button2.setVisible(True)
                self.FinalJWagersWindowui.button3.setVisible(True)
                self.FinalJWagersWindowui.button4.setVisible(True)
                self.FinalJWagersWindowui.button5.setVisible(True)
                self.FinalJWagersWindowui.button6.setVisible(True)
                self.FinalJWagersWindowui.button7.setVisible(True)
                self.FinalJWagersWindowui.button8.setVisible(True)
                self.FinalJWagersWindowui.button9.setVisible(True)
                self.FinalJWagersWindowui.buttonDEL.setVisible(True)
                self.FinalJWagersWindowui.buttonENTER.setVisible(True)
                self.FinalJWagersWindowui.correctButton.setVisible(False)
                self.FinalJWagersWindowui.incorrectButton.setVisible(False)
                self.FinalJWagersWindowui.ReponseLabel.setText("Enter " + scoresArray[index][1] + "'s wager: $" + wagerAmount)


    #this function handles all the button presses within the DailyDouble window. It's probably poorly written but it works
    def wagersButton(self, button):
          global wagerAmount
          global index

          maxWager = scoresArray[index][0]

          if button == "DEL" and wagerAmount != "":
                 wagerAmount = wagerAmount[:-1]
          elif button == "DEL" and wagerAmount == "":
                 pass
          elif button == "ENTER" and wagerAmount != "":
                 if int(wagerAmount) <= maxWager and int(wagerAmount) >= 5:
                        self.FinalJWagersWindowui.button0.setVisible(False)
                        self.FinalJWagersWindowui.button1.setVisible(False)
                        self.FinalJWagersWindowui.button2.setVisible(False)
                        self.FinalJWagersWindowui.button3.setVisible(False)
                        self.FinalJWagersWindowui.button4.setVisible(False)
                        self.FinalJWagersWindowui.button5.setVisible(False)
                        self.FinalJWagersWindowui.button6.setVisible(False)
                        self.FinalJWagersWindowui.button7.setVisible(False)
                        self.FinalJWagersWindowui.button8.setVisible(False)
                        self.FinalJWagersWindowui.button9.setVisible(False)
                        self.FinalJWagersWindowui.buttonDEL.setVisible(False)
                        self.FinalJWagersWindowui.buttonENTER.setVisible(False)
                        self.FinalJWagersWindowui.correctButton.setVisible(True)
                        self.FinalJWagersWindowui.incorrectButton.setVisible(True)
                 else:
                        pass
          elif button == "0" and wagerAmount == "0":
                 pass
          elif button == "ENTER" and wagerAmount == "":
                 pass
          else: 
                if int(wagerAmount + button) <= maxWager:
                         wagerAmount = wagerAmount + button
          self.FinalJWagersWindowui.ReponseLabel.setText("Enter " + scoresArray[index][1] + "'s wager: $" + wagerAmount)


    def showClueClicked(self):
        self.showClueButton.setVisible(False)

    def startMusicClicked(self):
        self.startMusicButton.setVisible(False)
        self.timer = QTimer()
        self.timer.setSingleShot(True)
        self.timer.timeout.connect(self.timeFinished)
        self.timer.start(3000) # 30,000 milliseconds = 30 seconds

    def timeFinished(self):
        global player1Score
        global player2Score
        global player3Score
        global player4Score
        global player5Score
        global scoresArray
        global nextWager

        self.FinalJWagersWindow = QtWidgets.QMainWindow()
        self.FinalJWagersWindowui = Ui_FinalJWagersWindow()
        self.FinalJWagersWindowui.setupUi(self.FinalJWagersWindow)
        self.FinalJWagersWindow.setWindowFlags(Qt.FramelessWindowHint)
        self.FinalJWagersWindow.show()

        self.setScores("self.FinalJWagersWindowui")

        self.FinalJWagersWindowui.CloseButton.clicked.connect(self.closedButtonClicked)
        self.FinalJWagersWindowui.button0.clicked.connect(lambda: self.wagersButton(button="0"))
        self.FinalJWagersWindowui.button1.clicked.connect(lambda: self.wagersButton(button="1"))
        self.FinalJWagersWindowui.button2.clicked.connect(lambda: self.wagersButton(button="2"))
        self.FinalJWagersWindowui.button3.clicked.connect(lambda: self.wagersButton(button="3"))
        self.FinalJWagersWindowui.button4.clicked.connect(lambda: self.wagersButton(button="4"))
        self.FinalJWagersWindowui.button5.clicked.connect(lambda: self.wagersButton(button="5"))
        self.FinalJWagersWindowui.button6.clicked.connect(lambda: self.wagersButton(button="6"))
        self.FinalJWagersWindowui.button7.clicked.connect(lambda: self.wagersButton(button="7"))
        self.FinalJWagersWindowui.button8.clicked.connect(lambda: self.wagersButton(button="8"))
        self.FinalJWagersWindowui.button9.clicked.connect(lambda: self.wagersButton(button="9"))
        self.FinalJWagersWindowui.buttonDEL.clicked.connect(lambda: self.wagersButton(button="DEL"))
        self.FinalJWagersWindowui.buttonENTER.clicked.connect(lambda: self.wagersButton(button="ENTER"))
        self.FinalJWagersWindowui.correctButton.clicked.connect(lambda: self.correctOrIncorrect(correct=True))
        self.FinalJWagersWindowui.incorrectButton.clicked.connect(lambda: self.correctOrIncorrect(correct=False))
        self.FinalJWagersWindowui.correctButton.setVisible(False)
        self.FinalJWagersWindowui.incorrectButton.setVisible(False)

        scoresArray = [(player1Score, "Player1"), (player2Score, "Player2"), (player3Score, "Player3"), (player4Score, "Player4"), (player5Score, "Player5")]
        #sort elements
        scoresArray = sorted(scoresArray, key=lambda x: x[0])
        # Remove elements with integer <= 0
        scoresArray = [item for item in scoresArray if item[0] > 0]
        print(scoresArray)    


        self.FinalJWagersWindowui.ReponseLabel.setText("Enter " + scoresArray[0][1] + "'s wager: $" + wagerAmount)

    def closedButtonClicked(self):
        FinalJWindow.close()
        self.FinalJWagersWindow.close()

    def setupUi(self, FinalJWindow):
        FinalJWindow.setObjectName("FinalJWindow")
        FinalJWindow.resize(1824, 600)
        FinalJWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(FinalJWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PS_DecoLabel = QtWidgets.QLabel(self.centralwidget)
        self.PS_DecoLabel.setGeometry(QtCore.QRect(20, 540, 984, 60))
        self.PS_DecoLabel.setStyleSheet("background-color: #060CE9;")
        self.PS_DecoLabel.setText("")
        self.PS_DecoLabel.setObjectName("PS_DecoLabel")
        self.PS_P1Name = QtWidgets.QLabel(self.centralwidget)
        self.PS_P1Name.setGeometry(QtCore.QRect(59, 545, 150, 25))

        QFontDatabase.addApplicationFont("Fonts/Swiss 911 Compressed Regular.otf")
        QFontDatabase.addApplicationFont("Fonts/JeopardyPi/Korinna-Regular.otf")
        QFontDatabase.addApplicationFont("Fonts/Univers 75 Black Regular.otf")

        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PS_P1Name.setFont(font)
        self.PS_P1Name.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.PS_P1Name.setAlignment(QtCore.Qt.AlignCenter)
        self.PS_P1Name.setObjectName("PS_P1Name")
        self.PS_P1Money = QtWidgets.QLabel(self.centralwidget)
        self.PS_P1Money.setGeometry(QtCore.QRect(59, 570, 150, 25))
        font = QtGui.QFont()
        font.setFamily("Univers 75 Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.PS_P1Money.setFont(font)
        self.PS_P1Money.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.PS_P1Money.setAlignment(QtCore.Qt.AlignCenter)
        self.PS_P1Money.setObjectName("PS_P1Money")
        self.PS_P2Name = QtWidgets.QLabel(self.centralwidget)
        self.PS_P2Name.setGeometry(QtCore.QRect(248, 545, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PS_P2Name.setFont(font)
        self.PS_P2Name.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.PS_P2Name.setAlignment(QtCore.Qt.AlignCenter)
        self.PS_P2Name.setObjectName("PS_P2Name")
        self.PS_P3Name = QtWidgets.QLabel(self.centralwidget)
        self.PS_P3Name.setGeometry(QtCore.QRect(437, 545, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PS_P3Name.setFont(font)
        self.PS_P3Name.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.PS_P3Name.setAlignment(QtCore.Qt.AlignCenter)
        self.PS_P3Name.setObjectName("PS_P3Name")
        self.PS_P4Name = QtWidgets.QLabel(self.centralwidget)
        self.PS_P4Name.setGeometry(QtCore.QRect(626, 545, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PS_P4Name.setFont(font)
        self.PS_P4Name.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.PS_P4Name.setAlignment(QtCore.Qt.AlignCenter)
        self.PS_P4Name.setObjectName("PS_P4Name")
        self.PS_P5Name = QtWidgets.QLabel(self.centralwidget)
        self.PS_P5Name.setGeometry(QtCore.QRect(815, 545, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PS_P5Name.setFont(font)
        self.PS_P5Name.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.PS_P5Name.setAlignment(QtCore.Qt.AlignCenter)
        self.PS_P5Name.setObjectName("PS_P5Name")
        self.PS_P2Money = QtWidgets.QLabel(self.centralwidget)
        self.PS_P2Money.setGeometry(QtCore.QRect(248, 570, 150, 25))
        font = QtGui.QFont()
        font.setFamily("Univers 75 Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.PS_P2Money.setFont(font)
        self.PS_P2Money.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.PS_P2Money.setAlignment(QtCore.Qt.AlignCenter)
        self.PS_P2Money.setObjectName("PS_P2Money")
        self.PS_P3Money = QtWidgets.QLabel(self.centralwidget)
        self.PS_P3Money.setGeometry(QtCore.QRect(437, 570, 150, 25))
        font = QtGui.QFont()
        font.setFamily("Univers 75 Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.PS_P3Money.setFont(font)
        self.PS_P3Money.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.PS_P3Money.setAlignment(QtCore.Qt.AlignCenter)
        self.PS_P3Money.setObjectName("PS_P3Money")
        self.PS_P4Money = QtWidgets.QLabel(self.centralwidget)
        self.PS_P4Money.setGeometry(QtCore.QRect(626, 570, 150, 25))
        font = QtGui.QFont()
        font.setFamily("Univers 75 Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.PS_P4Money.setFont(font)
        self.PS_P4Money.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.PS_P4Money.setAlignment(QtCore.Qt.AlignCenter)
        self.PS_P4Money.setObjectName("PS_P4Money")
        self.PS_P5Money = QtWidgets.QLabel(self.centralwidget)
        self.PS_P5Money.setGeometry(QtCore.QRect(815, 570, 150, 25))
        font = QtGui.QFont()
        font.setFamily("Univers 75 Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.PS_P5Money.setFont(font)
        self.PS_P5Money.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.PS_P5Money.setAlignment(QtCore.Qt.AlignCenter)
        self.PS_P5Money.setObjectName("PS_P5Money")
        self.CloseButton = QtWidgets.QPushButton(self.centralwidget)
        self.CloseButton.setGeometry(QtCore.QRect(1764, 10, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.CloseButton.setFont(font)
        self.CloseButton.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.CloseButton.setObjectName("CloseButton")
        self.AS_P5Name = QtWidgets.QLabel(self.centralwidget)
        self.AS_P5Name.setGeometry(QtCore.QRect(1029, 425, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AS_P5Name.setFont(font)
        self.AS_P5Name.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.AS_P5Name.setAlignment(QtCore.Qt.AlignCenter)
        self.AS_P5Name.setObjectName("AS_P5Name")
        self.AS_DecoLabel = QtWidgets.QLabel(self.centralwidget)
        self.AS_DecoLabel.setGeometry(QtCore.QRect(1024, 420, 800, 60))
        self.AS_DecoLabel.setStyleSheet("background-color: #060CE9;")
        self.AS_DecoLabel.setText("")
        self.AS_DecoLabel.setObjectName("AS_DecoLabel")
        self.AS_P4Name = QtWidgets.QLabel(self.centralwidget)
        self.AS_P4Name.setGeometry(QtCore.QRect(1189, 425, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AS_P4Name.setFont(font)
        self.AS_P4Name.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.AS_P4Name.setAlignment(QtCore.Qt.AlignCenter)
        self.AS_P4Name.setObjectName("AS_P4Name")
        self.AS_P3Name = QtWidgets.QLabel(self.centralwidget)
        self.AS_P3Name.setGeometry(QtCore.QRect(1349, 425, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AS_P3Name.setFont(font)
        self.AS_P3Name.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.AS_P3Name.setAlignment(QtCore.Qt.AlignCenter)
        self.AS_P3Name.setObjectName("AS_P3Name")
        self.AS_P2Name = QtWidgets.QLabel(self.centralwidget)
        self.AS_P2Name.setGeometry(QtCore.QRect(1509, 425, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AS_P2Name.setFont(font)
        self.AS_P2Name.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.AS_P2Name.setAlignment(QtCore.Qt.AlignCenter)
        self.AS_P2Name.setObjectName("AS_P2Name")
        self.AS_P1Name = QtWidgets.QLabel(self.centralwidget)
        self.AS_P1Name.setGeometry(QtCore.QRect(1669, 425, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AS_P1Name.setFont(font)
        self.AS_P1Name.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.AS_P1Name.setAlignment(QtCore.Qt.AlignCenter)
        self.AS_P1Name.setObjectName("AS_P1Name")
        self.AS_P5Money = QtWidgets.QLabel(self.centralwidget)
        self.AS_P5Money.setGeometry(QtCore.QRect(1029, 450, 150, 25))
        font = QtGui.QFont()
        font.setFamily("Univers 75 Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.AS_P5Money.setFont(font)
        self.AS_P5Money.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.AS_P5Money.setAlignment(QtCore.Qt.AlignCenter)
        self.AS_P5Money.setObjectName("AS_P5Money")
        self.AS_P4Money = QtWidgets.QLabel(self.centralwidget)
        self.AS_P4Money.setGeometry(QtCore.QRect(1189, 450, 150, 25))
        font = QtGui.QFont()
        font.setFamily("Univers 75 Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.AS_P4Money.setFont(font)
        self.AS_P4Money.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.AS_P4Money.setAlignment(QtCore.Qt.AlignCenter)
        self.AS_P4Money.setObjectName("AS_P4Money")
        self.AS_P3Money = QtWidgets.QLabel(self.centralwidget)
        self.AS_P3Money.setGeometry(QtCore.QRect(1349, 450, 150, 25))
        font = QtGui.QFont()
        font.setFamily("Univers 75 Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.AS_P3Money.setFont(font)
        self.AS_P3Money.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.AS_P3Money.setAlignment(QtCore.Qt.AlignCenter)
        self.AS_P3Money.setObjectName("AS_P3Money")
        self.AS_P2Money = QtWidgets.QLabel(self.centralwidget)
        self.AS_P2Money.setGeometry(QtCore.QRect(1509, 450, 150, 25))
        font = QtGui.QFont()
        font.setFamily("Univers 75 Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.AS_P2Money.setFont(font)
        self.AS_P2Money.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.AS_P2Money.setAlignment(QtCore.Qt.AlignCenter)
        self.AS_P2Money.setObjectName("AS_P2Money")
        self.AS_P1Money = QtWidgets.QLabel(self.centralwidget)
        self.AS_P1Money.setGeometry(QtCore.QRect(1669, 450, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AS_P1Money.setFont(font)
        self.AS_P1Money.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.AS_P1Money.setAlignment(QtCore.Qt.AlignCenter)
        self.AS_P1Money.setObjectName("AS_P1Money")
        self.AS_DecoLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.AS_DecoLabel2.setGeometry(QtCore.QRect(1024, 70, 801, 341))
        self.AS_DecoLabel2.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.AS_DecoLabel2.setText("")
        self.AS_DecoLabel2.setObjectName("AS_DecoLabel2")
        self.PS_DecoLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.PS_DecoLabel2.setGeometry(QtCore.QRect(20, 0, 984, 524))
        self.PS_DecoLabel2.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.PS_DecoLabel2.setText("")
        self.PS_DecoLabel2.setObjectName("PS_DecoLabel2")
        self.SettingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.SettingsButton.setGeometry(QtCore.QRect(1034, 10, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.SettingsButton.setFont(font)
        self.SettingsButton.setStyleSheet("QPushButton { background-color: transparent; border: 0px }")
        self.SettingsButton.setText("")
        self.SettingsButton.setObjectName("SettingsButton")
        self.SettingsLabel = QtWidgets.QLabel(self.centralwidget)
        self.SettingsLabel.setGeometry(QtCore.QRect(1034, 10, 50, 50))
        self.SettingsLabel.setText("")
        self.SettingsLabel.setPixmap(QtGui.QPixmap("settingsGear.jpg"))
        self.SettingsLabel.setObjectName("SettingsLabel")
        self.CategoryLabel = QtWidgets.QLabel(self.centralwidget)
        self.CategoryLabel.setGeometry(QtCore.QRect(434, 0, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.CategoryLabel.setFont(font)
        self.CategoryLabel.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.CategoryLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CategoryLabel.setWordWrap(True)
        self.CategoryLabel.setObjectName("CategoryLabel")
        self.PS_ClueLabel = QtWidgets.QLabel(self.centralwidget)
        self.PS_ClueLabel.setGeometry(QtCore.QRect(112, 80, 800, 431))
        font = QtGui.QFont()
        font.setFamily("Swiss 911 Compressed")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.PS_ClueLabel.setFont(font)
        self.PS_ClueLabel.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.PS_ClueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PS_ClueLabel.setWordWrap(True)
        self.PS_ClueLabel.setObjectName("PS_ClueLabel")
        self.AS_ClueLabel = QtWidgets.QLabel(self.centralwidget)
        self.AS_ClueLabel.setGeometry(QtCore.QRect(1024, 70, 800, 231))
        font = QtGui.QFont()
        font.setFamily("ITC Korinna Bold")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.AS_ClueLabel.setFont(font)
        self.AS_ClueLabel.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.AS_ClueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.AS_ClueLabel.setWordWrap(True)
        self.AS_ClueLabel.setObjectName("AS_ClueLabel")
        self.showClueButton = QtWidgets.QPushButton(self.centralwidget)
        self.showClueButton.setGeometry(QtCore.QRect(1224, 371, 400, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.showClueButton.setFont(font)
        self.showClueButton.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.showClueButton.setObjectName("showClueButton")
        self.ReponseLabel = QtWidgets.QLabel(self.centralwidget)
        self.ReponseLabel.setGeometry(QtCore.QRect(1024, 301, 800, 50))
        font = QtGui.QFont()
        font.setFamily("ITC Korinna Bold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ReponseLabel.setFont(font)
        self.ReponseLabel.setStyleSheet("background-color: #060CE9;\n"
"color: rgb(255, 255, 255);")
        self.ReponseLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ReponseLabel.setWordWrap(True)
        self.ReponseLabel.setObjectName("ReponseLabel")
        self.startMusicButton = QtWidgets.QPushButton(self.centralwidget)
        self.startMusicButton.setGeometry(QtCore.QRect(1224, 371, 400, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.startMusicButton.setFont(font)
        self.startMusicButton.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.startMusicButton.setObjectName("startMusicButton")
        self.AS_DecoLabel2.raise_()
        self.startMusicButton.raise_()
        self.SettingsLabel.raise_()
        self.PS_DecoLabel2.raise_()
        self.AS_DecoLabel.raise_()
        self.PS_DecoLabel.raise_()
        self.PS_P1Name.raise_()
        self.PS_P1Money.raise_()
        self.PS_P2Name.raise_()
        self.PS_P3Name.raise_()
        self.PS_P4Name.raise_()
        self.PS_P5Name.raise_()
        self.PS_P2Money.raise_()
        self.PS_P3Money.raise_()
        self.PS_P4Money.raise_()
        self.PS_P5Money.raise_()
        self.CloseButton.raise_()
        self.AS_P5Name.raise_()
        self.AS_P4Name.raise_()
        self.AS_P3Name.raise_()
        self.AS_P2Name.raise_()
        self.AS_P1Name.raise_()
        self.AS_P5Money.raise_()
        self.AS_P4Money.raise_()
        self.AS_P3Money.raise_()
        self.AS_P2Money.raise_()
        self.AS_P1Money.raise_()
        self.SettingsButton.raise_()
        self.CategoryLabel.raise_()
        self.PS_ClueLabel.raise_()
        self.AS_ClueLabel.raise_()
        self.ReponseLabel.raise_()
        self.showClueButton.raise_()
        FinalJWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(FinalJWindow)
        QtCore.QMetaObject.connectSlotsByName(FinalJWindow)
        
        self.showClueButton.clicked.connect(self.showClueClicked)
        self.startMusicButton.clicked.connect(self.startMusicClicked)
        self.CloseButton.clicked.connect(self.closedButtonClicked)

    def retranslateUi(self, FinalJWindow):
        _translate = QtCore.QCoreApplication.translate
        FinalJWindow.setWindowTitle(_translate("FinalJWindow", "MainWindow"))
        self.PS_P1Name.setText(_translate("FinalJWindow", "Player1"))
        self.PS_P1Money.setText(_translate("FinalJWindow", "$0"))
        self.PS_P2Name.setText(_translate("FinalJWindow", "Player2"))
        self.PS_P3Name.setText(_translate("FinalJWindow", "Player3"))
        self.PS_P4Name.setText(_translate("FinalJWindow", "Player4"))
        self.PS_P5Name.setText(_translate("FinalJWindow", "Player5"))
        self.PS_P2Money.setText(_translate("FinalJWindow", "$0"))
        self.PS_P3Money.setText(_translate("FinalJWindow", "$0"))
        self.PS_P4Money.setText(_translate("FinalJWindow", "$0"))
        self.PS_P5Money.setText(_translate("FinalJWindow", "$0"))
        self.CloseButton.setText(_translate("FinalJWindow", "X"))
        self.AS_P5Name.setText(_translate("FinalJWindow", "Player5"))
        self.AS_P4Name.setText(_translate("FinalJWindow", "Player4"))
        self.AS_P3Name.setText(_translate("FinalJWindow", "Player3"))
        self.AS_P2Name.setText(_translate("FinalJWindow", "Player2"))
        self.AS_P1Name.setText(_translate("FinalJWindow", "Player1"))
        self.AS_P5Money.setText(_translate("FinalJWindow", "$0"))
        self.AS_P4Money.setText(_translate("FinalJWindow", "$0"))
        self.AS_P3Money.setText(_translate("FinalJWindow", "$0"))
        self.AS_P2Money.setText(_translate("FinalJWindow", "$0"))
        self.AS_P1Money.setText(_translate("FinalJWindow", "$0"))
        self.CategoryLabel.setText(_translate("FinalJWindow", "Cat second"))
        self.PS_ClueLabel.setText(_translate("FinalJWindow", "Cat first, then clue, also change font"))
        self.AS_ClueLabel.setText(_translate("FinalJWindow", "The category is: "))
        self.showClueButton.setText(_translate("FinalJWindow", "Show Clue"))
        self.ReponseLabel.setText(_translate("FinalJWindow", "Wait for players to make wagers."))
        self.startMusicButton.setText(_translate("FinalJWindow", "Start Music"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FinalJWindow = QtWidgets.QMainWindow()
    ui = Ui_FinalJWindow()
    ui.setupUi(FinalJWindow)
    FinalJWindow.show()
    sys.exit(app.exec_())
