# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlayerClueWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlayerClueWindow(object):
    def setupUi(self, PlayerClueWindow):
        PlayerClueWindow.setObjectName("PlayerClueWindow")
        #PlayerClueWindow.resize(984, 540)
        PlayerClueWindow.setGeometry(20, 0, 984, 540)
        PlayerClueWindow.setStyleSheet("background-color: rgb(6, 12, 233);")
        self.centralwidget = QtWidgets.QWidget(PlayerClueWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CategoryLabel = QtWidgets.QLabel(self.centralwidget)
        self.CategoryLabel.setGeometry(QtCore.QRect(304, 0, 157, 78))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.CategoryLabel.setFont(font)
        self.CategoryLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.CategoryLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CategoryLabel.setObjectName("CategoryLabel")
        self.AmountLabel = QtWidgets.QLabel(self.centralwidget)
        self.AmountLabel.setGeometry(QtCore.QRect(461, 0, 219, 78))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.AmountLabel.setFont(font)
        self.AmountLabel.setStyleSheet("color: #d69f4c;")
        self.AmountLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.AmountLabel.setObjectName("AmountLabel")
        self.ClueLabel = QtWidgets.QLabel(self.centralwidget)
        self.ClueLabel.setGeometry(QtCore.QRect(0, 78, 984, 462))
        font = QtGui.QFont()
        font.setFamily("Script")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.ClueLabel.setFont(font)
        self.ClueLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.ClueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ClueLabel.setObjectName("ClueLabel")
        PlayerClueWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(PlayerClueWindow)
        QtCore.QMetaObject.connectSlotsByName(PlayerClueWindow)

    def retranslateUi(self, PlayerClueWindow):
        _translate = QtCore.QCoreApplication.translate
        PlayerClueWindow.setWindowTitle(_translate("PlayerClueWindow", "MainWindow"))
        self.CategoryLabel.setText(_translate("PlayerClueWindow", "Category"))
        self.AmountLabel.setText(_translate("PlayerClueWindow", "$10000"))
        self.ClueLabel.setText(_translate("PlayerClueWindow", "This is the clue"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PlayerClueWindow = QtWidgets.QMainWindow()
    ui = Ui_PlayerClueWindow()
    ui.setupUi(PlayerClueWindow)
    PlayerClueWindow.show()
    sys.exit(app.exec_())
