# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import resource  # Import the generated resource file

class Ui_GroupBox(object):
    def setupUi(self, GroupBox):
        GroupBox.setObjectName("GroupBox")
        GroupBox.resize(600, 600)
        GroupBox.setStyleSheet("background-color: rgb(0, 0, 0);")
        
        self.verticalLayout = QtWidgets.QVBoxLayout(GroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.pushButton = QtWidgets.QPushButton(GroupBox)
        self.pushButton.setStyleSheet("color: rgb(6, 12, 233);\n"
                                      "background-image: url(:/images/200.png);\n"
                                      "background-color: rgb(6, 12, 233);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.pushButton.setMinimumSize(100, 100)  # Set a minimum size for the button
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(GroupBox)
        QtCore.QMetaObject.connectSlotsByName(GroupBox)

    def retranslateUi(self, GroupBox):
        _translate = QtCore.QCoreApplication.translate
        GroupBox.setWindowTitle(_translate("GroupBox", "GroupBox"))
